### ISSUE TITLE
Interpreter features

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-core#10]
This issue tracks the features we eventually want out of the interpreter

- [x] Execute bytecode
- [x] Return error codes in some standard (e.g. JSON)
- [x] Return return values in some standard (e.g. JSON)
- [x] Gas profiling (total gas, gas per op, gas per line)
- [x] Bytecode coverage
- [x] Debugging
    - [x] Set breakpoints
    - [x] Step through code, continue to next breakpoint, etc.
    - [x] View entire memory space and registers

**Comment by Dentosal** [comment]
There have been all implemented. Consider opening a new issue in the fuel-vm repo if new features are needed.
