### ISSUE TITLE
Outdated osx build.

### ISSUE THREAD

**Issue by cold-briu** [FuelLabs/fuel-core#1023]
So, I'm having issues with fuel-core on mac 

My specs: 
`MacBook Pro (13-inch, Mid 2012) Intel Core i5 // osx 10.14.6 (18G9323)`

Installing from 
`https://fuellabs.github.io/fuelup/fuelup-init.sh `

Installed:
- forc 0.35.1
- forc-explore 0.28.1
- forc-index 0.2.3
- forc-wallet 0.1.3
- fuel-core 0.17.2
- fuel-indexer 0.2.3

Then go for toolchain
`$ fuelup toolchain install latest`
`'latest-x86_64-apple-darwin' is already installed and up to date`

⚠️ The issue: 
`$ fuel-core`

`dyld: Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /[my_stuff]/.fuelup/bin/fuel-core (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib`
  
**Please be aware that macOS Sierra 10.12 was released in 2016 7yrs ago**

**Comment by cold-briu** [comment]
btw not sure if it's my machine but this takes so long.

`$ cargo xtask build`
   `Compiling librocksdb-sys v0.8.3+7.4.4`
`    Building [=======================> ] 341/346: librocksdb-sys(build)`

**Comment by cold-briu** [comment]
It took a while, then

  Running `target/debug/xtask build`
error: failed to download from `https://crates.io/api/v1/crates/hyper-rustls/0.22.1/download`

Caused by:
  [60] Peer certificate cannot be authenticated with given CA certificates (SSL certificate problem: certificate has expired)
Error: "cargo build failed"

**Comment by leviathanbeak** [comment]
hi @cold-briu seems you don't have `proto buff` installed
it's listed under [System Requirments](https://github.com/FuelLabs/fuel-core/blob/master/README.md#macos)

**Comment by cold-briu** [comment]
> hi @cold-briu seems you don't have `proto buff` installed it's listed under [System Requirments](https://github.com/FuelLabs/fuel-core/blob/master/README.md#macos)

Hello there! 
Thanks for following up! 
Yes, you are right: I had issues building fuel-core btw the main issue is that **the crate is providing an outdated build** 

However I have good news: I've managed to build fuel-core after updating to osx 10.15.7 (19H2026)

How can I help solving this issue? 
😭 I spent half of my day bc of ` /[my_stuff]/.fuelup/bin/fuel-core (which was built for Mac OS X 12.0) `

**Comment by leviathanbeak** [comment]
I think it would be better to raise the issue on the `fuelup` side instead of `fuel-core` ?

**Comment by cold-briu** [comment]
Hello there! 
I've managed to build from source and I'm actively working on sway projects. 
However I would love to see and updated version of the x86 darwin binaries in the official distribution. I'm sure many people might come we te same issue.

**Comment by xgreenx** [comment]
Won't fix
