### ISSUE TITLE
Investigate Beta Fuel Core High CPU Usage

### ISSUE THREAD

**Issue by rfuelsh** [FuelLabs/fuel-core#1034]
Investigate the usage of fuel-core in beta2 namespace

% kubectl get pods -A -o wide | grep ip-172-34-8-2.ec2.internal
amazon-cloudwatch   fluent-bit-wxd6l                                         1/1     Running   0              43d   172.34.8.2      ip-172-34-8-2.ec2.internal      <none>           <none>
beta2               fuel-core-k8s-69f7cb6d48-nm7sg                           1/1     Running   1 (33d ago)    34d   172.34.5.1      ip-172-34-8-2.ec2.internal      <none>           <none>
kube-system         aws-node-qcc6g                                           1/1     Running   0              43d   172.34.8.2      ip-172-34-8-2.ec2.internal      <none>           <none>
kube-system         ebs-csi-node-swkxs                                       3/3     Running   0              43d   172.34.3.3      ip-172-34-8-2.ec2.internal      <none>           <none>
kube-system         kube-proxy-gl82q                                         1/1     Running   0              43d   172.34.8.2      ip-172-34-8-2.ec2.internal      <none>           <none>
monitoring          kube-prometheus-prometheus-node-exporter-rbp26           1/1     Running   0              43d   172.34.8.2      ip-172-34-8-2.ec2.internal      <none>           <none>

**Comment by BossHog1313** [comment]
Cool. I'll start on this soon.

**Comment by rfuelsh** [comment]
working with @BossHog1313 on this

**Comment by BossHog1313** [comment]
Working on this now.

**Comment by BossHog1313** [comment]
We have not seen this particular issue in roughly ten days. However, I'm going to use this time gathering some good profiling and investigative Kubernetes/Docker tools to investigate these problems in detail. Just in case. Ideally, an application can be probed when it becomes CPU intensive (or IO bound) and we can get close to the problem area.

**Comment by rfuelsh** [comment]
@BossHog1313 - this issue appeared- https://fuellabs.slack.com/archives/C0404RYSQHK/p1678716462240029 - today at 10:07 am

**Comment by BossHog1313** [comment]
I'll take a brief look. If I understand @Voxelot correctly, this is a problem limited to beta2 in production, and will disappear once beta3 is deployed there.

**Comment by Voxelot** [comment]
will reopen if cpu issues appear in beta3
