### ISSUE TITLE
Transactions can be lost in the network

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1049]
Due to various reasons(disconnection at the moment of transaction broadcasting; non-actual state of the transaction broadcaster/receiver) transactions can be lost in the network.

For the cases like this, we need a transaction reconciliation protocol. Where missed transactions can be synced again.

**Comment by freesig** [comment]
Goal: Make mempool more resilient.

**Comment by MitchTurner** [comment]
Closed with #2131
