### ISSUE TITLE
Prune spent coins from OwnedCoins column

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1053]
The explorer doesn't need to query previously spent coins by owner, so we should prune spent coins from this index to speed up coin selection.

**Comment by xgreenx** [comment]
But we support the `coins` request that returns spent and unspent coins. It means we do not need to support this endpoint.

**Comment by Voxelot** [comment]
Agreed, we should only return unspent coins from this endpoint.

**Comment by Voxelot** [comment]
Actually we already filter that API to only return unspent coins in beta2.

**Comment by xgreenx** [comment]
Yeah, I changed the behavior to return all coins for beta3 because SDK expected all coins.

I think we need to rename it to `unspent_coins` and prune also spent messages.

**Comment by Voxelot** [comment]
We should probably also make this as a patch for beta3 to avoid perf issues there.
