### ISSUE TITLE
Refactor DiscoveryBehaviour events in p2p

### ISSUE THREAD

**Issue by leviathanbeak** [FuelLabs/fuel-core#1065]
At this moment there is no need for other Behaviours / Swarm to listen to internal Discovery events so they should be removed.
Upon removing the Discovery test should be updated too.

**Comment by MitchTurner** [comment]
> At this moment there is no need for other Behaviours / Swarm to listen to internal Discovery events so they should be removed.

We want to keep the `DiscoveryBehavior`, right? I'm not sure how we remove the `DiscoveryEvent`s without removing the behavior. I don't believe any other behaviors are currently using the `DiscoveryEvent`s...
