### ISSUE TITLE
Create Nightly GA Action CI pipeline that runs cargo audit (fuel-core)

### ISSUE THREAD

**Issue by rfuelsh** [FuelLabs/fuel-core#107]
be some kind of nightly github action that runs cargo-audit - https://crates.io/crates/cargo-audit - on our repos to alert us of any yanked deps or other security issues

**Comment by xgreenx** [comment]
Hmm, maybe it is already done? Because I see we have this workflow https://github.com/FuelLabs/fuel-core/actions/runs/4049442666

**Comment by Voxelot** [comment]
We already have cardo-audit running
