### ISSUE TITLE
investigate gradual memory increase

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1070]
In prod there is a gradual increase in memory usage for our nodes. We need to find out if this is a memory leak or just rocksdb caching.

![image](https://user-images.githubusercontent.com/794823/226773788-ca6bd6fb-fe08-4f47-ba83-53ab6e3c8030.png)

**Comment by MitchTurner** [comment]
This doesn't cause the nodes to crash. As of today, the authority node has been running for 40 days without going down.

Perhaps if it was getting hit with more traffic, or by larger requests, it might crash. We should understand why this is filling up memory and how it will behave.

**Comment by xgreenx** [comment]
Closing for now since we don't see the problem anymore in the testnet
