### ISSUE TITLE
Client returns empty vector on failed receipts request

### ISSUE THREAD

**Issue by MujkicA** [FuelLabs/fuel-core#1074]
When requesting receipts for a transaction, the corresponding client endpoint will return an empty vector on failure.
This makes it hard for the SDK to determine if the request failed.

As pointed out by @xgreenx, the problem is [here](https://github.com/FuelLabs/fuel-core/blob/f7ff66ed43b1140e53640b312414fc820a75c7bb/crates/client/src/client.rs#L553)

**Comment by xgreenx** [comment]
The endpoint returns `Result<Option<Vec<Receipt>>>` while the client does `unwrap_or_default`. Either we need to return `None` on SDK side, or return `NotFound` error from the endpoint and client.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/18346821/227948239-dcffaa91-34e1-4bd0-8efc-89a78c1d66ee.png">

**Comment by Voxelot** [comment]
I think we should return None if there's no receipts as not all transactions are expected to return receipts.

Some examples:
 - Transaction is waiting in the txpool to be included in a block and hasn't been processed yet
 - The transaction is of type create or mint, and doesn't have any receipts.
 - We enable receipt pruning on older transactions.

I think returning a `NotFound` error only makes sense in the context where we expected a resource to exist but it's not available for some unknown reason.

**Comment by xgreenx** [comment]
Fixed in the 0.18 release
