### ISSUE TITLE
Client returns empty vector on failed receipts request

### ISSUE THREAD

**Issue by MujkicA** [FuelLabs/fuel-core#1075]
When requesting receipts for a transaction, the corresponding client endpoint will return an empty vector on failure.
This makes it hard for the SDK to determine if the request failed.

As pointed out by @xgreenx, the problem is here [here](https://github.com/FuelLabs/fuel-core/blob/f7ff66ed43b1140e53640b312414fc820a75c7bb/crates/client/src/client.rs#L553)

**Comment by MujkicA** [comment]
Duplicate

**Comment by xgreenx** [comment]
The endpoint returns `Result<Option<Vec<Receipt>>>` while the client does `unwrap_or_default`. Either we need to return `None` on SDK side, or return `NotFound` error from the endpoint and client.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/18346821/227948239-dcffaa91-34e1-4bd0-8efc-89a78c1d66ee.png">
