### ISSUE TITLE
Efficient Database Encoding

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1085]
We currently use serde for encoding our data structures. However, this is suboptimal because our serde implementation for types like `Byte32` uses hex encoding to support common API and genesis configuration formats. This means that as we store or retrieve data, it will have to encode/decode these types to and from hex strings.

This should be addressed by the following:

1. Move serde back to using the native types and avoid stringifying data. This would have to be done in a way that doesn't break downstream API consumers.
2. Use an alternate serialization library such as rkyv.
3. Build our own serializers for the database, similar to how we did for the VM memory format but more space efficient.

**Comment by mitchmindtree** [comment]
> Use an alternate serialization library such as rkyv.

It may also be worth considering `zerovec` for this role: https://docs.rs/zerovec/latest/zerovec/.

While both achieve a similar goal, each have trade-offs:

- `zerovec`'s zero-copy deserialization is compatible with the existing `serde` traits, unlike `rkyv` which requires its own `Serialize`/`Deserialize` traits.
- With `zerovec` we'd maintain control over the serializable type, whereas `rkyv` will generate a new `Archived` type from a derive (probably doesn't matter).

[This presentation](https://www.youtube.com/watch?v=DM2DI3ZI_BQ) by Manish (a long-time rust-lang contributor) was a good overview.

I'm sure `rkyv` would work well, just thought I'd mention `zerovec` for consideration.

---

Slight tangent, but whatever format we settle on, I suspect we could probably also use the same format for a network representation of a transaction too.

**Comment by Voxelot** [comment]
Zero-copy serialization aside, the main crux of the issue is the way we are using serde. Since we use serde for formatting our types in API responses and tooling, the serde impl is geared towards supporting that usecase. For example, when using serde_json on a `fuel_tx::Transaction`, there's no way to make `Bytes32` render as a hex-string without changing the serde representation for everything else (even when using bincode). This leads to inefficient binary encoding when using serde adapters since we don't have the ability to differentiate how certain types should be serialized depending on the adapter.

**Comment by Voxelot** [comment]
Actually looking into this further, it seems like serde provides a way to resolve this issue using `is_human_readable`!

https://docs.rs/serde/1.0.163/serde/trait.Serializer.html#method.is_human_readable

So by defining our own custom serde impl, we might be able to alternate between human readable hex strings vs compact binary representations!

**Comment by freesig** [comment]
Seems like there is two potential issues here.
1. Use `is_human_readable` to give API responses that are different to the database / network serialization (which should be more optimized for size).
2. Using a zero-copy serialization so we can avoid deserialiazing from the database or network.

Can I split this issue up and we work on 1. first?

**Comment by Voxelot** [comment]
blocked by #1195

**Comment by Voxelot** [comment]
@xgreenx  to investigate if the db footprint is lower after upgrade of fuel 0.33

**Comment by xgreenx** [comment]
Fixed with https://github.com/FuelLabs/fuel-vm/pull/454 and integrated with https://github.com/FuelLabs/fuel-core/pull/1195
