### ISSUE TITLE
Node Sync Throughput

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1089]
@xgreenx noticed that it can take up to several hours to sync ~50k blocks. We need to investigate whether requests are sufficiently batched for downloading blocks and if the importer is being fully utilized at maximal capacity. If the importer is actually being kept busy during sync and it's just taking a long time, then we need to investigate further into gas metering discrepancies and if the min block time is too low.

We should aim to have a benchmark / loadtest to measure syncing time between nodes.

**Comment by xgreenx** [comment]
- While we are executing blocks, we don't request new headers. It means that our flow is: Request 10 headers separately -> request transaction for each available header  -> execute 10 blocks -> repeat. It is all done sequentially.
Instead, we should start to request new headers immediately after block execution.
- Currently, we request each header one by one. Instead, it will be faster and better(from a performance perspective) to send the range of headers. In the same way, we need to request transactions - https://github.com/FuelLabs/fuel-core/issues/1133
- It would be nice to add some performance logs for the following events:
    - Block importing
    - Header request/response time
    - Transactions for header request/response time
It will help to track the performance of the synchronization process.
