### ISSUE TITLE
Reuse calculated tx id in executor

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1112]
Maybe we can calculate it one time at the begin of the `execute_create_or_script` method and pass it everywhere?

_Originally posted by @xgreenx in https://github.com/FuelLabs/fuel-core/pull/1107#discussion_r1160938395_

**Comment by xgreenx** [comment]
Fixed by https://github.com/FuelLabs/fuel-core/pull/1248
