### ISSUE TITLE
GraphQL client backend

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1122]
Client for GraphQL API. The GraphQL Client will implement the backend interface using the existing GraphQL queries and mutations. This separates the existing logic where the Client logic and GraphQL logic are coupled together. The GraphQL Client will be responsible for taking Fuel's backend-agnostic Rust types and converting them into a serializable format that GraphQL can send over the network. Similarly, the GraphQL Client will be responsible for receiving GraphQL server responses and converting GraphQL types back into Fuel Rust types.

Blocked by:
- https://github.com/FuelLabs/fuel-core/issues/1128

Acceptance Criteria:
- [ ] GraphQL Client implements the generic client backend interface using GraphQL specific logic
- [ ] GraphQL Client takes in [Client types](https://github.com/FuelLabs/fuel-core/issues/1121) from the Client and converts them to GraphQL types
- [ ] GraphQL Client receives GraphQL types from the GraphQL Server and converts them to Client types  
- [ ] GraphQL Client can be selected or turned off using a compiler flag

**Comment by xgreenx** [comment]
The `fuel-core-client` already has own types decoupled from `fuel-core`. The GraphQL still can rely on `fuel-core` types since it is built on top of the `fuel-core`
