### ISSUE TITLE
Fuel Service client backend

### ISSUE THREAD

**Issue by ghost** [FuelLabs/fuel-core#1126]
Client for embedded `FuelService` API. The `FuelService` Client will implement the backend interface by calling into a `FuelService` instance directly within the same binary. This should be a simple forwarding of arguments from the client to `FuelService`.  Since all communication is done directly at the application level, with no networked communication, there is no need for extra types to support serialization or deserialization (unlike GraphQL or RPC).

Blocked by:
- https://github.com/FuelLabs/fuel-core/issues/1128

Acceptance Criteria:
- [ ] `FuelService` Client implements the generic client backend interface by forwarding arguments to `FuelService`
- [ ] `FuelService` Client can be selected or turned off using a compiler flag

**Comment by xgreenx** [comment]
I don't think that we want to implement it anymore
