### ISSUE TITLE
Rust APIs in `FuelService` to communicate with service layer

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1127]
Currently, services in `fuel-core`, such as the Tx Pool, are invoked directly by GraphQL resolvers at the server API level. This creates a tight coupling between GraphQL and the services. Instead, we want to abstract service layer interaction by introducing a Rust API that has parity with the GraphQL API. 

GraphQL resolvers can then use this API to talk indirectly with the needed services (see #1123)

Acceptance Criteria:
- [ ] All GraphQL APIs are duplicated in a Rust API in `FuelService` to provide feature-parity
- [ ] All services are removed from `async-graphql` server context
- [ ] `FuelService` (or `SharedData`) is available to the `async-graphql` server context
- [ ] No GraphQL resolvers talk directly to service layer components

**Comment by MitchTurner** [comment]
This all makes a lot of sense. Just something to keep in mind: we already have a bunch of types working up to the GraphQL types, and we should carefully decide if the existing types should be on the Rust API interface or if we need new types to insulate ourselves from coupling.

**Comment by xgreenx** [comment]
This is already resolved since we used ports for GraphQL service
