### ISSUE TITLE
Interface for client backend

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1128]
The Client must be configurable to interface with any backend. The Client communicates with the backends using a backend client. To maximize modularity, we want to introduce an interface (a Rust trait or traits) that define the possible operations (queries, mutations, subscriptions) that the backend supports. 

Backend clients will implement this interface, and the Client can choose whichever backend client it desires to use at compile time: 
- GraphQL
- gRPC
- Directly embedded `FuelService`

Blocked by:
- [ ] https://github.com/FuelLabs/fuel-core/issues/1121

Acceptance Criteria:
- [ ] The trait(s) for client backends is defined
- [ ] All instances of the concrete GraphQL client are replaced with a polymorphic trait object

**Comment by xgreenx** [comment]
All requirements to the database in GraphQL service already use Rust traits, so it is done
