### ISSUE TITLE
GraphQL Client/Server integration

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1129]
Integrate the GraphQL Client Backend with the GraphQL server for FuelCore. 

This should result in all the integration tests passing when using the GraphQL Client & Server.

Blocked by: 
- [ ] https://github.com/FuelLabs/fuel-core/issues/1122
- [ ] https://github.com/FuelLabs/fuel-core/issues/1123

Acceptance Criteria:
 - [ ] When using GraphQL Client and Server, all integration tests pass

**Comment by Voxelot** [comment]
blocked by: #1125, #1122

**Comment by xgreenx** [comment]
Close since it can be part of the https://github.com/FuelLabs/fuel-core/issues/1123
