### ISSUE TITLE
gRPC Client/Server integration

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1130]
Integrate the gRPC Client Backend with the gRPC Server for FuelCore. 

This should result in all the integration tests passing when using the gRPC Client and Server.

Blocked by: 
- [ ] https://github.com/FuelLabs/fuel-core/issues/1124
- [ ] https://github.com/FuelLabs/fuel-core/issues/1125

Acceptance Criteria:
 - [ ] When using gRPC Client and Server, all integration tests pass

**Comment by xgreenx** [comment]
We will stick with GraphQL for now
