### ISSUE TITLE
State performance tests

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1134]
Add performance tests for contracts with lots of state and balances

- Bench insertion of 1 key/value pair into the `RocksDB` table that contains `[0, 1_000, 100_000, 10_000_000]` entries of *different* contracts.
- Bench insertion of 1 key/value pair into the `RocksDB` table that contains `[0, 1_000, 100_000, 10_000_000]` entries of *same* contracts.

**Comment by bvrooman** [comment]
I'm currently benchmarking with these configurations, but going forward, I propose that we reduce the benchmark with 10,000,000 entries to 1,000,000 because the setup takes hours.
