### ISSUE TITLE
Investigate RocksDB transactions as an alternative to in-memory transactions

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1139]
Now that the RocksDB crate supports built-in transactions, evaluate whether it would be possible and more efficient to use those in place of the in-memory data store.

https://docs.rs/rocksdb/0.20.1/rocksdb/struct.DBCommon.html#method.transaction

**Comment by xgreenx** [comment]
Close in favor https://github.com/FuelLabs/fuel-core/issues/1589
