### ISSUE TITLE
Implement I/O gas measurement

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-core#1161]
- [x] Add witness data limit via transaction policies
    - spec PR https://github.com/FuelLabs/fuel-specs/pull/514.
    - vm issue https://github.com/FuelLabs/fuel-vm/issues/576.
    - Implement refund for unused witnesses limit
- [x] https://github.com/FuelLabs/fuel-core/issues/1404
- [x] https://github.com/FuelLabs/fuel-vm/issues/602

Acceptance Criteria:

- Witness data is included in the base transaction fee for bytes
- Witness bytes can't exceed the witness data limit policy (if set)
- Storage read/write costs are adjusted to constrain excessive state growth long-term

**Comment by xgreenx** [comment]
All sub-issues are resolved
