### ISSUE TITLE
source ci_checks.sh

### ISSUE THREAD

**Issue by firedpeanut** [FuelLabs/fuel-core#1177]
running 7 tests
test can transfer from alice to bob                            ... ok
test can transfer from alice to bob and back                   ... ok
test can execute script and get receipts                       ... ok
test can dry run transfer script and get receipts              ... FAILED
test can transfer from alice to bob and back                   ... FAILED
test can execute script and get receipts                       ... FAILED
test dry run script that touches the contract with large state ... ok
test can dry run transfer script and get receipts              ... FAILED
test dry run transaction from `non_specific_tx.raw` file       ... FAILED
test can deploy a large contract                               ... FAILED

failures:

---- can dry run transfer script and get receipts ----
Error making HTTP request: error sending request for url (http://127.0.0.1:46103/graphql): error trying to connect: tcp open error: Too many open files (os error 24)

---- dry run script that touches the contract with large state ----
Failed to get status for transaction Some(Err(Custom { kind: Other, error: "Graphql error: HttpStream(hyper::Error(Connect, ConnectError(\"tcp open error\", Os { code: 24, kind: Uncategorized, message: \"Too many open files\" })))" }))

---- dry run transaction from `non_specific_tx.raw` file ----
Error making HTTP request: error sending request for url (http://127.0.0.1:46103/graphql): error trying to connect: tcp open error: Too many open files (os error 24)

---- can deploy a large contract ----
Failed to get status for transaction Some(Err(Custom { kind: Other, error: "Graphql error: HttpStream(hyper::Error(Connect, ConnectError(\"tcp open error\", Os { code: 24, kind: Uncategorized, message: \"Too many open files\" })))" }))

failures:
    can dry run transfer script and get receipts
    dry run script that touches the contract with large state
    dry run transaction from `non_specific_tx.raw` file
    can deploy a large contract

test result: FAILED. 3 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 51.27s

error: test failed, to rerun pass `-p fuel-core-e2e-client --test integration_tests`

**Comment by xgreenx** [comment]
The dry run tests create a lot of simultaneous connections to the server, it requires a socket. You can increase the number of sockets https://www.howtogeek.com/805629/too-many-open-files-linux/

**Comment by firedpeanut** [comment]
thank you.
