### ISSUE TITLE
Add logging of the long GraphQL queries for future debug

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1186]
We need to add detailed logging into the resolver for long GraphQL queries for future debugging.

**Comment by Agilulfe** [comment]
I can happily give it a go.

**Comment by xgreenx** [comment]
You can try to finish it, but we plan to start work on it the next week, so you need to hurry=)

**Comment by Agilulfe** [comment]
You can go for it then. I thought it was stale and wanted to casually get my hands dirty.

**Comment by xgreenx** [comment]
Done with https://github.com/FuelLabs/fuel-core/pull/1250
