### ISSUE TITLE
Investigate why node gets stuck at cpu saturation in beta-3 test net (until restart)

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1190]
Sometimes some in the beta3 got 100%(800% for eight cores) CPU load. We have a hot loop that consumes all CPU. 

It would be useful to add more metrics https://github.com/FuelLabs/fuel-core/issues/1168 to identify the service that has troubles. Initial idea: Maybe it is p2p service

**Comment by d3287t328** [comment]
Can you give more info on CPU types and any error messages?

**Comment by xgreenx** [comment]
Close for now as won't fox
