### ISSUE TITLE
Extract types from `fuel-core-client` into a separate `no_std` compatible crate

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1212]
Extract [types](https://github.com/FuelLabs/fuel-core/tree/master/crates/client/src/client) from `fuel-core-client` into a separate `no_std` compatible crate. 

- Create a new `fuel-core-client-types` crate with `schema` inside
- Update CI to check that we can compile this crate with `wasm32-unknown-unknown`
- Update `ci_checks.sh` script

**Comment by ra0x3** [comment]
- Just an FYI that I tried (slash am trying) to implement this. 
- @xgreenx would this involve moving `types` _and_ `schema`? 
- Also, how do I (if it's needed) invoke this `build.rs` script? 
- (Totally fine to punt on this if you think someone on your team can do this faster/better)

**Comment by xgreenx** [comment]
It is blocked by https://github.com/FuelLabs/fuel-vm/issues/443

**Comment by xgreenx** [comment]
Fixed in the https://github.com/FuelLabs/fuel-core/pull/1411
