### ISSUE TITLE
Expose `GasCost` from the `chain_info` endpoint

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1221]
The SDK can't get `GasCosts` from the `fuel-core` because we don't expose this information. The `chain_info` endpoint should also include `GasCosts` along with `ConsensusParametrs`

**Comment by danielbate** [comment]
Is there any update on this? I believe this is blocking us as we are not retrieving a `predicateGasUsed` property from the `estimate-predicates` endpoint.

**Comment by xgreenx** [comment]
The `estimate_predicates` should return transaction with estimated predicates to you=)
<img width="735" alt="image" src="https://github.com/FuelLabs/fuel-core/assets/18346821/49c1e215-8e6d-49ce-8587-da16fa86aee8">

**Comment by danielbate** [comment]
Thankyou, this has now been resolved for us, please disregard

**Comment by lucasgstz** [comment]
Good one Daniel, i was looking all those emails just now... No sense at all...
N1
TY

________________________________
De: Daniel Bate ***@***.***>
Enviado: terça-feira, 11 de julho de 2023 10:07
Para: FuelLabs/fuel-core ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [FuelLabs/fuel-core] Expose `GasCost` from the `chain_info` endpoint (Issue #1221)


Thankyou, this has now been resolved for us, please disregard my comment

**Comment by xgreenx** [comment]
Fixed with https://github.com/FuelLabs/fuel-core/pull/1244
