### ISSUE TITLE
Capitalize GQL field descriptions

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuel-core#123]
As seen in the image below, descriptions of fields in GQL Playground are uncapitalized and look weird.

![image](https://user-images.githubusercontent.com/412180/148663941-9fbae662-b79b-4761-a746-add01e17c2e1.png)

We should note that some descriptions are derived from doc comments like in below:
![image](https://user-images.githubusercontent.com/412180/148664044-2bbb4dcd-a5be-4fff-9b60-2f954d8212a9.png)

For that reason, it might make sense to start capitalizing all doc comments (or even all comments) instead of just capitalizing the ones async-graphql read. (cc @Voxelot)

I think we could go even further and start capitalizing all comments on all repos.

While there are ESLint rules like `capitalized-comments` and `spaced-comment` to style comments a bit ([demo](https://eslint.org/demo#eyJ0ZXh0IjoiLy8gbG93ZXJcbi8vbm8gbGVhZGluZyBzcGFjZSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY2FwaXRhbGl6ZWQtY29tbWVudHMiOjIsInNwYWNlZC1jb21tZW50IjoyfSwiZW52Ijp7fX19)) it doesn't seem like equivalents exist in the Rust ecosystem.

There are generic CI tools that could enforce this or we could contribute these rules to Clippy, but I don't think we have to go there at this time.

**Comment by ControlCplusControlV** [comment]
I can tackle this issue, it would just mean changing the name of the rust structs which are then used to generate the GraphQL correct? Or would `fuel-core interfaces` require any tweaking?

**Comment by adlerjohn** [comment]
> start capitalizing all doc comments

I believe this is about comments only, but I'll let @AlicanC clarify.

**Comment by ControlCplusControlV** [comment]
Checked the query in question](https://github.com/FuelLabs/fuel-core/blob/master/fuel-core/src/schema/coin.rs#L50 ) and it is comments, knew graphQL was derived from the Rust file, but didn't remember if description was made from the comments or a [separate field like this one](https://github.com/FuelLabs/fuel-core/blob/master/fuel-core/src/schema/tx.rs#L40)

**Comment by AlicanC** [comment]
@ControlCplusControlV, those two links you gave are both valid examples of what's in scope of this issue. Rust struct names do change the schema but they look all fine so nothing needs to be done there.
