### ISSUE TITLE
Peer info subscription

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1242]
Peers subscription:
- [ ] `get_peer_updates()` method on network service to create subscription to P2P events like peer connect and disconnect
- [ ] P2P events are published to the subscription with the peer ID and peer event for all peers
- [ ] GraphQL endpoint for calling `get_peer_updates()` and peer events are published to a websocket
- [ ] `get_peer_updates()` on client queries GraphQL endpoint for peer updates

**Comment by xgreenx** [comment]
Blocked by https://github.com/FuelLabs/fuel-core/issues/649

**Comment by MitchTurner** [comment]
@Voxelot We aren't sure if this is needed anymore, or why we need this. Do you have any context for us, or should we scrap this?

**Comment by xgreenx** [comment]
Closing since we don't see a reason
