### ISSUE TITLE
Decompose `ConsensusParameters` struct into more relevant structs

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#1243]
Let's break down `ConsensusParameters` into structs based on how they are used, rather than stuffing every value into one struct.

For example the fields that are used for calculating Tx cost could be included in a `TxParams` struct and the fields that include `max` values, could be in a `DataLimit` struct.

It is also possible that fields that are not included in `ConsensusParameters` but are used with it would be better off in the `TxParams`. Look at fields on `ChainInfo`, for example.

Related to: https://github.com/FuelLabs/fuel-core/issues/1221

**Comment by xgreenx** [comment]
I want to clarify that the idea is to keep the `ConsensusParameters` structure and put there all data required for consensus(Like `GasCosts`, storage costs, `TxParametrs`, etc). But to avoid the mess with million fields, we need to extract fields into their own structures based on usage context.

**Comment by xgreenx** [comment]
Finished with https://github.com/FuelLabs/fuel-core/pull/1262
