### ISSUE TITLE
Process the storage error during response

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1278]
<img width="1597" alt="image" src="https://github.com/FuelLabs/fuel-core/assets/18346821/885aef98-57b5-40df-a9e0-e35dbfe077fb">

If the node has problems retrieving data from the storage, we need to log it and send the `None` back to the caller instead of silent do nothing.

**Comment by MitchTurner** [comment]
I'm gonna wait until https://github.com/FuelLabs/fuel-core/issues/1133 is done before working on this.

**Comment by xgreenx** [comment]
Closed with https://github.com/FuelLabs/fuel-core/pull/1342
