### ISSUE TITLE
Handle overflows of configuration variables

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-core#1282]
Currently multiple configuration variables are used in a way that could cause an integer overflow. The values must be either constrained and validated when reading the config, or the overflows must be handled when they occur.

For instance this could overflow with weird configuration values

https://github.com/FuelLabs/fuel-core/blob/e551f309e2dfb4ed94fd9bd0a17fd75b79bad563/crates/services/p2p/src/p2p_service.rs#L170-L173

**Comment by xgreenx** [comment]
Done during https://github.com/FuelLabs/fuel-core/pull/1466
