### ISSUE TITLE
Pending block, used gas estimation, dry run

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-core#129]
txpool submit as Brandon said should return the result of tx inclusion inside txpool. When somebody wants to submit a signed transaction it needs to be sure that the transaction is already checked and with submit the user tell us it's the intention to commit, it is mostly a point of no return because tx is going to be broadcasted to the network. 

There is an idea of the pending block, where the Block producer will every `N` second take best `T` transactions and with its best ability create pending block so that users know what to expect (this is just usability, it shouldn't have any effect on consensus) and can inspect executed transactions.

There should be the ability to dry run tx (or maybe even a list of tx if they are dependent) so that users can see gas used and calculate the gas limit. Dry run over the pending block or dry run over the best block. This can be even extended to: with this gas_price where is this transaction going to land inside the block and what amount of gas is going to be used, there are some MEV vibes here but seems like a topic for the future.

**Comment by Voxelot** [comment]
@rakita we already have a dry-run interface, we should either clearly specify the improvements needed or close this issue.

**Comment by rakita** [comment]
This is different, it gives you best gues on next block that is going to be created and it better reflects changes that are going to be merged into canon chain.
dry-run is still needed for gas estimations, testing, getters etc.. but this dry-run is agains pending block not agains best known block, and user can chose if he want pending, best or past block to dry-run agains.

**Comment by xgreenx** [comment]
Close in favour of https://github.com/FuelLabs/fuel-core/issues/1206
