### ISSUE TITLE
Fix DA Height Raising logic and tests

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#1292]
In the `set_raises_da_height_monotonically` tests, there is a test
`#[test_case(11, None, 10; "inserts are bypassed when height reverted from 11 to 10")]`

This should not be possible, nor should it be a test. After all, it should be increasing "monotonically"

All of the tests are bad though, since none of them check outputs. Modify the tests to do some checks and add some failure modes.

**Comment by xgreenx** [comment]
We don't have mentioned test anymore=)
