### ISSUE TITLE
Allow `manual_blocks_enabled` only with `debug` feature enabled during compilation

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1297]
From the comment: https://github.com/FuelLabs/fuel-core/pull/1286/files#r1290825419

Blocked by https://github.com/FuelLabs/fuel-core/issues/1296

**Comment by Voxelot** [comment]
As discussed, this should be a cli arg feature flag rather than a compile flag. Otherwise it will impact the ability of the released binaries to be used by sdk harnesses etc.
