### ISSUE TITLE
Investigate Workflow Templating

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#130]
We're currently copying and pasting a lot of our CI configuration around. We should look into consolidating release or docker image publishing workflows into parameterizable templates: https://docs.github.com/en/actions/learn-github-actions/creating-starter-workflows-for-your-organization

**Comment by rfuelsh** [comment]
There is a concept of re-usable workflows which basically use an existing workflow in the same folder and calls upon to be used in the job:

https://docs.github.com/en/actions/using-workflows/reusing-workflows#reusable-workflows-and-starter-workflows

Example is:

`name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}`
