### ISSUE TITLE
fuel-core-keygen not uploaded to release artifacts

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1300]
In order for users to be able to generate their libp2p keys for peering with the network, they need to be able to download and run the `fuel-core-keygen` cli. Currently it looks like our binary release process isn't creating proper release artifacts for this cli tool.

An alternative is to add p2p keygen to the forc-wallet plugin, or embed it into the fuel-core cli itself.

**Comment by xgreenx** [comment]
The `fuel-core-keygen` is part of the archive with `fuel-core` binary.

**Comment by Voxelot** [comment]
ah ok 👍🏻 

We'll just need to see what's needed to ensure this is handled properly in fuelup

cc @kayagokalp
