### ISSUE TITLE
Allow for API to return block producer address

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-core#1305]
I was doing some profiling of the Fuel indexer service and I found the following information while looking at the resultant flamegraph:

![Output from cargo-flamegraph showing the block_producer() method leading to expensive crypto signature validation](https://github.com/FuelLabs/fuel-core/assets/9167686/acc1386d-563a-4a0c-acad-e83bcb0035e9)

The above section shows that the underlying work done by `block.block_producer()` method is almost entirely dominated by signature recovery; this particular operation accounts for ~13% of the entire sample set. The Fuel indexer doesn't need to validate crypto signatures as all we want to do is just get the address of the block producer.

@Voxelot mentioned that it's up to the client to recover the address from the signature, which I agree is good for security as you may want to verify that the address is correct. However, a canonical indexer service would be connected to a trusted Fuel node and it would be reasonable to trust that the producer address is correct. Thus, is it possible that the `fuel-core` API can be adjusted to also return the block producer address for applications that may not need to validate/recover the signature?

**Comment by MitchTurner** [comment]
YAGNI

**Comment by deekerno** [comment]
I agree that I'm not gonna need it. 😉

Closing this.
