### ISSUE TITLE
Download range of transactions during syncing

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1315]
Ref https://github.com/FuelLabs/fuel-core/issues/1133

Instead of fetching transactions per header, add a new p2p API that allows entire ranges of blocks to be downloaded from a peer.

**Comment by bvrooman** [comment]
To clarify: by "range of blocks", I believe this means something more like "list of blocks", since block IDs are not continuous (versus block heights, which are continuous). In my current WIP, the new API takes in a vector of block IDs, rather than a range.

**Comment by xgreenx** [comment]
It's up to us. We can request transactions by the range of block heights instead of block ids. 

On the blockchain level we don't have use cases for list of ids, its more API node kind functionality and maybe indexer will provide that.
