### ISSUE TITLE
Add an endpoint to return the status of the bridged message

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1323]
We use the `SpentMessages` table internally for the relayer and executor. But on the bridge UI we need to know the status of messages. There is a workaround based on the DA height, but it is safer to provide an endpoint to fetch this kind of information.

<img width="894" alt="image" src="https://github.com/FuelLabs/fuel-core/assets/18346821/d9264493-8b08-416a-9491-3da510c714bd">

**Comment by MitchTurner** [comment]
I assume that this endpoint is meant to be on the client? And the bridge UI will have access to the client?

**Comment by xgreenx** [comment]
We need to implement it in the `crates/fuel-core/src/schema` directory as we did for all API and provide a getter from `fuel-core-client`. The next step depends on the typescript SDK team.

**Comment by xgreenx** [comment]
Fixed with https://github.com/FuelLabs/fuel-core/pull/1371
