### ISSUE TITLE
`cargo xtask build` fails to build on master due to missing conversion

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1337]
Currently, `cargo xtask build` fails on master (**edit: unreleased**)  due to compilation errors in `crates/fuel-core/src/schema/chain.rs`. 

This blocks building the GQL schema.

An example of this error is:
```
error[E0277]: the trait bound `scalars::U64: std::convert::From<fuel_core_types::fuel_tx::DependentCost>` is not satisfied
   --> crates/fuel-core/src/schema/chain.rs:430:21
    |
430 |         self.0.s256.into()
    |                     ^^^^ the trait `std::convert::From<fuel_core_types::fuel_tx::DependentCost>` is not implemented for `scalars::U64`
```

The root cause of this failure appears to be some of the getter functions inside the implementation of `GasCosts`. Here, we are trying to convert `DependentCost`, which is a 2 dimensional value, to a single dimensional scalar. 

These getter functions don't appear to be used anywhere, so it may be safe to simply update the signature to return a tuple of values when using `DependentCost`.

**Comment by bvrooman** [comment]
Turns out, this failure is the simply the result of using `fuel-core` master with an unreleased version of `fuel-vm` master. Since the version isn't released, failure is expected. The attached PR could be helpful for adopting the next `fuel-vm` version into `fuel-core`.

**Comment by wuliuqii** [comment]
I also get an error when I tried to run `cargo xtask build` with fuel.nix, are they the same problem? I create a issue in https://github.com/FuelLabs/fuel.nix/issues/100.

![image](https://github.com/FuelLabs/fuel.nix/assets/34090258/9999de63-673a-4718-ad20-66770b6b6397)

**Comment by bvrooman** [comment]
That appears to be a separate issue that you're experiencing. If you like, feel free to submit a new ticket for the issue you're experiencing.
