### ISSUE TITLE
Random peer selection based on reputation for Request/Response protocol

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1344]

**Comment by MitchTurner** [comment]
We need to decide if this is still needed, since we might already do random selection.

**Comment by AurelienFT** [comment]
Yes it's indeed random based on the peers we know have the block that correspond to an height : https://github.com/FuelLabs/fuel-core/blob/0a1d591b3c1d041cbd53ca7417f88a020af0932d/crates/services/p2p/src/peer_manager.rs#L228
