### ISSUE TITLE
Add receipts to status subscription

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1364]
We currently have a way to submit a transaction which also creates a subscription to the transaction status. However, most users of the node will still need to fetch the receipts after receiving the final status update. This requires the use of sticky sessions to ensure that the 2nd request for receipts goes to the same node that provided the status update.

Instead, we should include receipts on the final status update in the subscription. This simplifies the logic in the sdk to avoid making multiple requests, and also guarantees consistency without needing to use sticky sessions.

**Comment by xgreenx** [comment]
Some notes regarding the implementation:

1. Add `receipts` to the `SuccessStatus`


![Image](https://github.com/FuelLabs/fuel-core/assets/18346821/efa21508-d16d-47eb-886e-d7c4dc54b128)

2. Add `receipts` to the `FailureStatus`


![Image](https://github.com/FuelLabs/fuel-core/assets/18346821/5d7540ef-55f4-4706-b4c0-cc42ca0a5c1c)



3. And update `submit_and_await_commit_with_receipts` function to fetch receipts in one request
![Image](https://github.com/FuelLabs/fuel-core/assets/18346821/ec815d07-cbf7-4f75-b67f-7b0b2cb04d55)
