### ISSUE TITLE
Remove `asset_id` field from `MessageCoin`

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1365]
Makes sense given the context that this is on a MessageCoin, as it should be implicit that the amount of the asset is related to the base id.

However, from a user perspective it could also be confusing if they are trying to understand how to parse messages. Since if an erc20 is bridged, they may confuse the amount and asset with the erc20 coin they wanted to bridge, which would actually be encoded into the data section.

Since it's implicit anyways, do we even need the asset field here at all?

_Originally posted by @Voxelot in https://github.com/FuelLabs/fuel-core/pull/1339#discussion_r1325081219_

**Comment by xgreenx** [comment]
I think it is better to keep `asset_id` because it allows to fetch all information about the coin in one query. Without it we need to request `chain_info` with `ConsensusParameters` to be able to identify the base `AssetId`.
