### ISSUE TITLE
`launch_custom_provider_and_get_wallets` panics on MAC

### ISSUE THREAD

**Issue by blackbeam** [FuelLabs/fuel-core#1368]
I believe the actual reason is https://github.com/rust-lang/rust/issues/100141

The panic message is 

```
thread 'basic' panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:424:33
```

The backtrace points to [this line](https://github.com/FuelLabs/fuel-core/blob/02f6d880977dd196826dc52edc6a34e0b5afac6e/crates/services/consensus_module/poa/src/service.rs#L205) in fuel-core.

**Comment by xgreenx** [comment]
It was solved in the https://github.com/FuelLabs/fuel-core/pull/1466/files#diff-763b2fd40e7f1ad277c50ff36407a7d8ef9479857efd290e3e57cd1cd12b55e4.

The fix should be available starting `fuel-core 0.21`
