### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO) and LLVM BOLT

### ISSUE THREAD

**Issue by zamazan4ik** [FuelLabs/fuel-core#1369]
Hi!

Recently I did many Profile-Guided Optimization (PGO) benchmarks on many projects - the results are available [here](https://github.com/zamazan4ik/awesome-pgo) (and much more PGO-related information). So that's why I think it's worth trying to apply PGO to Fuel.

I can suggest the following things to do:
* Evaluate PGO's applicability to Fuel via benchmarking.
* If PGO helps to achieve better performance - add a note to Fuel's documentation about that. In this case, users and maintainers will be aware of another optimization opportunity for Fuel.
* Provide PGO integration into the build scripts. It can help users and maintainers easily apply PGO for their own workloads.
* Optimize prebuilt Fuel binaries with PGO.

After PGO, I can suggest evaluating [LLVM BOLT](https://github.com/llvm/llvm-project/blob/main/bolt/README.md) as an additional optimization step after PGO.

For the Rust projects, I recommend starting with [cargo-pgo](https://github.com/Kobzol/cargo-pgo).

**Comment by xgreenx** [comment]
Thank you for creating an issue=)We don't have plans right now to look into PGO, but maybe we will look into it later
