### ISSUE TITLE
Create tool that returns a contract for block producer with hardcoded public key inside

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1409]
Related https://github.com/FuelLabs/fuel-core/issues/1269

**Comment by MitchTurner** [comment]
> Create tool that returns a contract for block producer with hardcoded public key inside
A tool where? Is this returning the code for a contract or somehow generating it on chain. Why do we want this?

**Comment by xgreenx** [comment]
> A tool where? 

As part of the `fuel-core` binary.

> Is this returning the code for a contract or somehow generating it on chain

The tool should return the bytecode of the contract.

> Why do we want this?

We want to put the bytecode of the generated contract in the chain config. The block producer will use this contract to accumulate and withdraw fees from blocks.
