### ISSUE TITLE
Add benchmarks for Push and Pop opcodes

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#1446]
## Overview

Currently, the opcodes `pshh`, `pshl`, `poph`, and `popl` aren't costed. We need to create benchmarks to cost those and confirm that the sanity benchmarks make sense as well.

Related to https://github.com/FuelLabs/fuel-core/pull/1444

## Implementation details

The `pshh` and `pshl` should be tested with a full bitmask `(1 << 24) - 1`. The same applies to `poph` and `popl`, but they require an initialization script that calls `pshh`/`pshl` with full bitmask.

**Comment by xgreenx** [comment]
Closed by https://github.com/FuelLabs/fuel-core/pull/1490
