### ISSUE TITLE
Make `gossip_heartbeat_interval` as a `Duration` and use `500ms` as default value

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1455]

**Comment by bvrooman** [comment]
I have a quick PR up that address the "essence" of this issue: https://github.com/FuelLabs/fuel-core/pull/1517. This PR changes the default to 500 milliseconds.

However, I'm not clear if this task is asking to change the `gossip_heartbeat_interval` type on `P2PArgs` from `u64` to `Duration`, or to simply change the default. If the goal is to simply change the default to 500 milliseconds, the above PR should be sufficient. If the goal is to change the type to `Duration`, I can also do that (using a [custom parser or humantime](https://stackoverflow.com/a/72314001)), but I am not sure if there is a material benefit to that.
