### ISSUE TITLE
`fuel-core-keygen` should support `--version` arg

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/fuel-core#1495]
Fuelup expects all components to implement the `--version` argument.

Related: https://github.com/FuelLabs/fuelup/issues/508

**Comment by richardgreg** [comment]
Hi @sdankel, I would like to take up this issue.

**Comment by sdankel** [comment]
> Hi @sdankel, I would like to take up this issue.

@richardgreg Feel free to send a PR 😄

**Comment by lilasxie** [comment]
@sdankel @richardgreg I have fixed this issue, can I take up this PR?
![image](https://github.com/FuelLabs/fuel-core/assets/30857671/36777cbe-acb8-40af-99fa-08bdbdfa19d0)

**Comment by richardgreg** [comment]
@lilasxie sure 👌
