### ISSUE TITLE
Sanity-check `gtf` opcodes

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#1499]
Following https://github.com/FuelLabs/fuel-core/issues/1386

Might not need to create a benchmark for every `gtf` opcode, but rather choose a good candidate for worst-case scenario.

Specifically, the opcodes that get metadata from inputs/outputs can take longer if there are more inputs/outputs. We might be able to choose a worst-case opcode and overcharge for the others since `gtf` isn't called many times in a single script.

**Comment by xgreenx** [comment]
Closed by https://github.com/FuelLabs/fuel-core/pull/1503
