### ISSUE TITLE
graph-node / firehose integration

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-core#1537]
This is a tracking issue for using [graph-node](https://github.com/graphprotocol/graph-node) as an indexing backend for fuel-core, with [Firehose](https://firehose.streamingfast.io/integrate-new-chains/integration-overview)-based data relaying.

This work is now tracked in https://github.com/FuelLabs/fuel-subgraph repo.

**Comment by digorithm** [comment]
Done.
