### ISSUE TITLE
Flakey integration test `partition_with_100_txs_8_validators_4_partitions`

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#1538]
Need to investigate a flakey integ test in CI, as it is causing many failures sporadically.

Test name: `partition_with_100_txs_8_validators_4_partitions`

Example of failed run: https://github.com/FuelLabs/fuel-core/actions/runs/7172189019/job/19528833109

**Comment by xgreenx** [comment]
Is fixed with latests modifications to p2p service. Potentially it also can fail because of problems with transaction broadcasting.
