### ISSUE TITLE
Abstract database to work with raw bytes instead of types

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1548]
### Overview

With each Fuel node, the data from the blockchain is stored in a database. The tables on the database expect specific types,  so as the blockchain evolves and those types change, we need the database to accept updated and new types.

The most general way of doing this is to always store the data as raw bytes, rather than strong types, and as those types change shape they can just be serialized accordingly.

### Design Thoughts/Questions

- What happens if a network update requires new tables added to the db, not just changes in the shape stored on the tables?
- What is stored on db is rawbytes, but the interface for the DB should just be a `non_exhaustive` `enum` right? We don't want to be stringly typed at our interface (port).

**Comment by MitchTurner** [comment]
Could the database types not just be an `non_exhaustive` `enum` instead of bytes? Maybe there's not a meaningful difference between that and what is proposed above since it all gets serialized anyway?
