### ISSUE TITLE
Regenesis supports migration of API-related tables

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1572]
The first 4 tables can be derived from the data available in the on-chain database, so we don't need to serialize them into the snapshot.
However, we need to write code and workers who will initialise these tables based on the on-chain data.

The data from the last 2 tables is not recoverable, so we need to serialise them into the snapshot file.
These tables should be migrate in the same way what is used for on-chain migration.

```rust
pub enum Column {
    /// The column of the table that stores `true` if `owner` owns `Coin` with `coin_id`
    OwnedCoins = 1,
    /// The column of the table of all `owner`'s transactions
    TransactionsByOwnerBlockIdx = 3,
    /// The column of the table that stores `true` if `owner` owns `Message` with `message_id`
    OwnedMessageIds = 4,
    /// See [`blocks::FuelBlockIdsToHeights`]
    FuelBlockIdsToHeights = 6,

    /// Transaction id to current status
    TransactionStatus = 2,
    /// The column of the table that stores statistic about the blockchain.
    Statistic = 5,
}
```

**Comment by Dentosal** [comment]
Is there anything more to do after https://github.com/FuelLabs/fuel-core/pull/1786?

**Comment by xgreenx** [comment]
Yep, https://github.com/FuelLabs/fuel-core/issues/1790
