### ISSUE TITLE
On-chain Migration Testing

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1608]
# Overview

To assess the correctness of on-chain migrations, we want:
- To perform a manual on-chain migration on the network
- To implement an integration test that performs an on-chain migration

## Manual on-chain migration test:
- Demonstrate that it is possible to perform an on-chan migration successfully
- Write the migration

## Integration test
- Reproducible integration test that gives us confidence in the underlying migration framework
- Prevent regressions that may break migrations

**Comment by xgreenx** [comment]
Maybe it is duplicate of the https://github.com/FuelLabs/fuel-core/issues/950. Or maybe it is a master issue and https://github.com/FuelLabs/fuel-core/issues/950 is a sub issue=) @bvrooman What do you think?

**Comment by xgreenx** [comment]
Main tests are done. Remaining testing will be done in the https://github.com/FuelLabs/fuel-core/issues/950
