### ISSUE TITLE
Off-chain database migration

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1619]

**Comment by MitchTurner** [comment]
I'm not sure if this is an issue or a feature. I think we should make a clearer distinction between those. Typically Scrum has Issues, Features, and Epochs, where issues are the smallest and features capture a group of issues and epochs capture a long-term business objective.

**Comment by xgreenx** [comment]
It is a master issue to track progress on the migration of the off-chain table. Since we decided to split migration into two parts, on-chain and off-chain, it has its own deliverables. The whole database migration belongs to the regenesis feature, but because the regenesis feature itself took 4 months, we need smaller tickets to track work=)

**Comment by xgreenx** [comment]
Is done as part of the https://github.com/FuelLabs/fuel-core/issues/1545
