### ISSUE TITLE
Make RocksDB more upgradeable

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#162]
Problem: Adding new column families to RocksDB breaks the database and requires a complete wipe.

We make extensive use of RocksDB column families to partition various data types. These column families are identified using integer based column id's configured in the [database columns constants module](https://github.com/FuelLabs/fuel-core/blob/master/fuel-core/src/database.rs#L35).

However, due to the way we open and initialize RocksDB, any new columns added to the schema breaks the database and it is no longer able to open. Adding new columns shouldn't break the entire database and require it to be scrapped.

The primary method involved is [RocksDb::open](https://github.com/FuelLabs/fuel-core/blob/master/fuel-core/src/state/rocks_db.rs#L24).

**Comment by simrankedia** [comment]
@Voxelot  I have tried to raise a PR to fix this issue https://github.com/FuelLabs/fuel-core/pull/1851 - please let me know if the direction is correct - I will accordingly complete and release a new PR with tests etc.
