### ISSUE TITLE
Add a test to verify that malleable fields don't affect validity of the block

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1620]
Add unit test to executor or integration test to the `fuel-core` that verifies validity of the block is not affected by the set malleable fields.

## Implementation details

The bytecode can take the hash of the transaction from VM memory and check that it is equal to the `tx_id` in the begging of the memory.

**Comment by Dentosal** [comment]
Included in https://github.com/FuelLabs/fuel-vm/pull/678

**Comment by xgreenx** [comment]
Done as part of the https://github.com/FuelLabs/fuel-core/pull/1714
