### ISSUE TITLE
Implement new `estimate_gas_price` api

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#1648]
It will take a block horizon and return what the most expensive the gas price will be over that horizon.

For now, it should just return the hard-coded value that is already available via the `NodeInfo`.

Followup to this work: https://github.com/FuelLabs/fuel-core/issues/1606

**Comment by Curraso** [comment]
f

**Comment by xgreenx** [comment]
@MitchTurner Do we need to rename `NodeInfo.min_gas_price` to `gas_price` as well?
