### ISSUE TITLE
Implement algorithm to predict gas price for `estimate_gas_price` endpoint

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#1653]
We are creating the interface earlier, to lower the number of downstream changes (to SDK etc). This task is for actually implementing something that takes the `block_horizon` and gives the caller an estimate for how much the gas price could change over that horizon.

**Comment by MitchTurner** [comment]
WIP Doc:
https://www.notion.so/fuellabs/Gas-Price-Algorithm-c421a5d9037d44f586bde0697aec90bc

**Comment by xgreenx** [comment]
Solved in https://github.com/FuelLabs/fuel-core/pull/1983
