### ISSUE TITLE
Upgradable `ContractsInfo` type

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1654]
# Background 

The `ContractsInfo` type is current the tuple `(Salt, Bytes32)` where the `Salt` records the salt used to create the contract, and the `Bytes32` is the Merkle root of the given contract. The salt is non-protocol level data, while the Merkle root is protocol level data. This coupling of non-protocol and protocol level data is unnecessary, and we can decouple these data points. 

# Solution

One solution stems from recognizing that we do not need to store the Merkle root in on-chain storage. During `CROO` execution, we can instead recalculate the contract's Merkle root from the contract data loaded from storage. This removes the dependency on `ContractInfo` during `CROO` and other on-chain operations. We can then remove the Merkle root from the `ContractsInfo` type and store only the salt, allowing `ContractsInfo` to be an `off-chain` only data type. 

With the simplified `ContractsInfo` type, we can apply the versioned enum idiom to allow simple upgrades.

## Criteria

- [x] Remove the contract root from the `ContractsInfo` table in `fuel-vm` (https://github.com/FuelLabs/fuel-vm/pull/673)
- [x] During `CROO`, the contract's root is recalculated reading the contract data from storage and applying the root calculation (https://github.com/FuelLabs/fuel-vm/pull/673)
- [x] The `ContractsInfo` type is versioned using an enum (https://github.com/FuelLabs/fuel-core/pull/1657)
- [ ] Move `ContractInfo` table to off-chain database

**Comment by xgreenx** [comment]
I'm closing this issue as fixed. The last sub-task will be done in a separate issue https://github.com/FuelLabs/fuel-core/issues/1721
