### ISSUE TITLE
Database/RocksDb Metrics

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#167]
Instrument the fuel-core database to collect telemetry metrics.

Some basic metrics for starters:
- read rate
- write rate
- cache statistics
- (additional metrics deemed useful)

**Comment by rfuelsh** [comment]
I can start to look into this, but is the purpose for prometheus to scrape the metrics of rockdb or configure metrics output on the db side?

**Comment by Voxelot** [comment]
We'd likely need to instrument the database ourselves in rust to generate the metrics. I don't think rocksdb comes with any built-in tracing or metrics we could use.

**Comment by Voxelot** [comment]
Adding @ControlCplusControlV to help implement the rustometer examples into the client.
