### ISSUE TITLE
Enhancing System Modularity: Decoupling End-User API Code from State Transition Functions

### ISSUE THREAD

**Issue by Omeiza559** [FuelLabs/fuel-core#1673]
1. Separate the end-user API-related code from the state transition function and encapsulate it within a distinct service architecture, thereby fostering modularity and enhancing the maintainability and scalability of the system.
2. Implement a clandestine API endpoint designed to clandestinely receive messages through Nonce authentication.

Thanks

**Comment by xgreenx** [comment]
Thank you for creating the issue. I will close it since it is not clear what the purpose is, and it looks like the desription is AI-generated. If it is not, you are welcome to reopen and add more description.
