### ISSUE TITLE
::::::::::: Add HYPERLANE route:::::::::::::



### ISSUE THREAD

**Issue by Sayan7388** [FuelLabs/fuel-core#1683]
I would suggest to Fuel network can connect with the route of hyperlane. This will increase the chances of the fuel ecosystem becoming much larger in near future. As a result fuel will be connected to the cosmos eco-system + EVM and the probability of many user shift will increase for the fuel eco-system. I strongly believe that we are going to in a modular era where transaction cost is low, TPS is very fast and this integration could bring us a new era of world of crypto. Can fuel open Hyperlane Route through FVM ??
🫡🫡

**Comment by xgreenx** [comment]
Thank you for creating the issue. We don't have plans for now to work in this direction. But maybe in the future...=)

**Comment by Sayan7388** [comment]
I am very excited for the modular future 🫡🍻
