### ISSUE TITLE
# Fuel network × Init capital ⛽

### ISSUE THREAD

**Issue by monojit786** [FuelLabs/fuel-core#1686]
"Init capital is a innovative project on mantel. It's solving liquidity problem in defi. We can bootstrapping fuel networks initial liquidity through init capital. It can help initially low liquidity problem of fuel networks daaps. For mass adoption fuel network can face initial liquidity problem , slippage issue. But now it can be solve guys. We can solve our daaps slippage issue and give our users better swap rates. If the partnership works then I think it's just a matter of time when we see mass adoption in fuel network".......
 

> Url links:   **( https://init.capital/)**

Thanks & Regards.

**Comment by xgreenx** [comment]
Hello, thank you for creating the issue. I'm closing this issue since we track questions related to the developments in GitHub. Any business stuff is better addressed through other channels.
