### ISSUE TITLE
MAKE FUEL  HOME OF ALL BY ADDING LOGX.TRADE 

### ISSUE THREAD

**Issue by Tiwatopeo** [FuelLabs/fuel-core#1695]
LogX perp dex with deep liquidity for a seamless and efficient leveraged trading experience. fully backed 
by COINBASE , IOSGVC, & HASHEDEM which you can learn more in the link below 

https://logx-1.gitbook.io/logx-docs/logx-perp-dex/overview

Fuel  is a preacher of  decentralized so having  a dex where  future traders can leverage will make FUEL the home of all.

#### 📋 Additional Context
Twitter page :-  https://x.com/LogX_trade

**Comment by Dentosal** [comment]
Now about no
