### ISSUE TITLE
State Revert / Replay

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#172]
We currently support transactional database views in fuel-core, however, we don't currently have the ability to revert a changeset. This will be needed in the case of things like re-orgs, or to replicate previous states as part of an IVG.

This will most likely involve the following:
 - New column family to store change sets, indexed by block id or height
 - Ability to go from the current state to a previous state using a change set
   - This will likely re-use a lot of the same mechanics as a transaction, where changed keys are kept in memory and keys that aren't found are retrieved from the backing data source.
  - Configuration options for pruning old changesets over time

**Comment by xgreenx** [comment]
Close in favour of https://github.com/FuelLabs/fuel-core/issues/451
