### ISSUE TITLE
Transactions selection algorithm should work in FIFO mode for transaction with the same price

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1739]
The transaction algorithm uses the `TxId` as a second key when tips are equal. This causes the starvation of old transactions and may lead to keeping users' transactions in the tx pool for a long time. We need to track when the transaction was submitted and use it as a second key.

<img width="1366" alt="image" src="https://github.com/FuelLabs/fuel-core/assets/18346821/0aefeb6d-7c8c-425a-839c-89c28456fb1e">

**Comment by Voxelot** [comment]
closed by #1964
