### ISSUE TITLE
The fuel header should mark imported content from the L1

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1741]
Currently, each node simply imports all events received from the ethereum node. But in the case if the ethereum node returns different events than expected, it is impossible to prove that the state is incorrect(like some messages are missed). It is not critical in the case of missing events because we can index them later. But in the case of incorrect events(not real events) it can bring the network into an incorrect state.

For the safety of the network, it would be better if the block producer also posts the hash of the imported events along with the `da_block_height`. In this case, we can easily prove/identify an incorrect state.

**Comment by Voxelot** [comment]
It might be better to make this a merkle root of imported events, and we'll also need to formally specify the event encoding format that is used to serialize these into bytes.

**Comment by xgreenx** [comment]
I think we can hash all fields emitted by the event. In this case L1 contract can do the same on his side and it will be enough during fraud prooving.
