### ISSUE TITLE
The block producer should take into account the total gas used by the L1 transactions

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1750]
Each forced transaction from L1 will also have a corresponding gas limit. The L1 contract is responsible for queuing transactions on L1 to not exceed the block gas limit.

Right now, the block producer service blindly increases the da block height to the last available height. However, this may cause a situation when we need to include more transactions than fit into the block gas limit. To avoid that, the block producer should take into account the gas used by the transactions from the L1.

**Comment by shexinyi9527** [comment]
how to account the  gas used by the L1 ?

**Comment by MitchTurner** [comment]
Clarification: This is for the L2 gas to include the L1 transactions on L2.
