### ISSUE TITLE
Upgradable consensus parameters

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1753]
- Make `ConsensusParameters` and `GasCost` versionable(`fuel-vm` and `fuel-core`).
- Create a new type of the transaction that allow permissioned upgrade of consensus parameters. It gasless, it should support predicates and signatures(it should be customisable).
- Add new table to store CP. Update application block header to contain version of the CP. Implement simple increasing of the version during procession of a new transaction. Update block producer and executor to use a new CP from the table.

**Comment by MitchTurner** [comment]
I feel like versions for CP could mean two things: change the values, but have the same fields, or add a new type with different/ new fields.

What are we thinking here?

**Comment by xgreenx** [comment]
It means both. The main point is to indicate that there are new consensus parameters. How exactly they look like is defined by serialization and deserialization.

**Comment by MitchTurner** [comment]
> It means both. The main point is to indicate that there are new consensus parameters. How exactly they look like is defined by serialization and deserialization.

Meaning that the mapping of a version to the params is for the serialized parameters and not for the current Rust type?

**Comment by xgreenx** [comment]
Yes. The database will contain a table where the key is a version, and the value is serialized consensus parameters.
