### ISSUE TITLE
E2E Testing for On-Chain Data

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#1763]
General test outline:

1. Setup the resource data to a known state on the node
2. Run regenesis on the node
3. Query the node for the resource state
4. Compare the resource state after regenesis to the known state
5. If the states are equal, the tests pass; otherwise, the tests fail

Criteria:

- [x] E2E test to confirm that contract states are consistent before and after regenesis (https://github.com/FuelLabs/fuel-core-regenesis/pull/1)
- [x] E2E test to confirm that contract balances are consistent before and after regenesis
  - Currently support base asset (https://github.com/FuelLabs/fuel-core-regenesis/pull/8)
  - Do we need other assets?
- [x] E2E test to confirm that coins are consistent before and after regenesis (https://github.com/FuelLabs/fuel-core-regenesis/pull/8)
- [x] E2E test to confirm that messages are consistent before and after regenesis (https://github.com/FuelLabs/fuel-core-regenesis/pull/8)

Aftermath testing:
- Test that all tables are consistent before and after regenesis via API calls
  - Blocks, contract balances, coins, messages
- Process
  - Get the resource via API call
  - Perform regenesis
  - Get the resource via API call again
  - Compare

**Comment by wilsommary676** [comment]
Please stay away from this investing online with these fake platforms . One really need to be careful of what they do online. I was a victim to this platform they made me lose all my funds and I was blocked by them and I was unable to reach them on Skype, But am glad I took the risk of working with Mr Jeff Silbert after I have heard so many review about her. She thought me a lot and with her guidance I was able to recover my funds which I lost to this platform. I can’t thank you enough Jeff by saving me from worst mistake is something I will forever be grateful for.  I highly recommend anyone in help on how to get your funds recovery Em ail.  jeffsilbert39  g m a il . c o m  I hope this reach out well to any victim. Stay Safe.
