### ISSUE TITLE
Stuck in Starting PoASyncTask service 

### ISSUE THREAD

**Issue by jzeah** [FuelLabs/fuel-core#1784]
I runned the command: fuel-core run --db-type in-memory --debug in wsl2 ubuntu22.04, but it stuck. 
![image](https://github.com/FuelLabs/fuel-core/assets/20739980/3cdd085c-0678-4e4e-8252-7d0c71434717)
![image](https://github.com/FuelLabs/fuel-core/assets/20739980/4c69e5bc-7fb3-4722-86f8-a006dc28d4df)

**Comment by xgreenx** [comment]
It is a normal log, and you haven't been stuck=D The default configuration for `fuel-core` only produces blocks when you submit a transaction, until that point you will not received any logs=)

I'm closing the issue for now
