### ISSUE TITLE
Fake GitHub stars?

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [FuelLabs/fuel-core#1815]
[Ethereum node](https://github.com/ethereum/go-ethereum) has fewer stars than your repository.

[![Star History Chart](https://api.star-history.com/svg?repos=FuelLabs/fuel-core&type=Date)](https://star-history.com/#FuelLabs/fuel-core&Date)

**Comment by Dentosal** [comment]
The number is indeed absurdly high. I tried looking into github traffic metrics, but they didn't provide any explanation. Fortunately, nobody should care about the stars anyway.

I'm closing this, as it's not an actual issue with the codebase.
