### ISSUE TITLE
Flaky  `test_peer_info` test in CI

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#1875]
Occasionally this test fails during `cargo test --all-features --workspace` with error:
```
failures:

---- node_info::test_peer_info stdout ----
thread 'node_info::test_peer_info' panicked at tests/tests/node_info.rs:95:5:
assertion `left == right` failed
  left: 1
 right: 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    node_info::test_peer_info

test result: FAILED. 187 passed; 1 failed; 3 ignored; 0 measured; 0 filtered out; finished in 134.90s
```
See here: https://github.com/FuelLabs/fuel-core/actions/runs/8904581067/job/24454081248

**Comment by AurelienFT** [comment]
Fixed here https://github.com/FuelLabs/fuel-core/pull/1609/files#diff-3ea0f35bf28d8c07e4ae1a2e007cb2df4f8860e36535799eeb8e6bf432f625c7R95-R106
