### ISSUE TITLE
Low level database access?

### ISSUE THREAD

**Issue by andy-thomason** [FuelLabs/fuel-core#1892]
It would be very useful to be able to access the database from an external process such as in the following example:

```Rust
fn access_database() -> anyhow::Result<()> {
    let path = Path::new("/data/fuel/data/fuel_beta5");
    let database = Database::open(path, None)?;

    let h = database.latest_height()?;
    println!("h={h}");
    Ok(())
}
```

We can do this with many blockchain nodes without stopping the service
and it provides a low-latency, high-throughput interface to the state of the node.
But it seems that the **rocksdb** database has a permanent lock on the LOCK file.

Perhaps there is something I don't understand or an alternative table-level interface
such as Erigon's KV gRPC (not ideal, but better than GraphQL).

If I am being an idiot, please say so!

**Comment by andy-thomason** [comment]
Thanks. @xgreenx 

I'll pass this on to Mahdi who is implementing data ingestion.

**Comment by malivix** [comment]
@xgreenx
For read only and secondary mode should call `try_catch_up_with_primary` but seems is not happening now, so will not data updated

**Comment by xgreenx** [comment]
Read only doesn't support `try_catch_up_with_primary`; only secondary mode supports it. You need to call it manually on your side=)
