### ISSUE TITLE
Investigate removing `DeadlineClock`

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#1917]
It got removed from one of its spots here:
https://github.com/FuelLabs/fuel-core/pull/1914

Might be worth looking at using `Interval` everywhere instead.

**Comment by Dentosal** [comment]
Issue here is that if we error during block production, new blocks wont be produced anymore and the service hangs.

**Comment by AurelienFT** [comment]
I don't have permission to assign myself yet, so placing this comment as an assignment placeholder
