### ISSUE TITLE
chore(docs):Typo in fee_calculations.md

### ISSUE THREAD

**Issue by vamsi4845** [FuelLabs/fuel-core#1926]
There's a typo in the fee_calculations.md file. In the storage fees section, "calculatoin" should be corrected to "calculation" for clarity and correctness

**Comment by xgreenx** [comment]
We don't want to have a lot of small PRs with fixes only for several typos. We want to fix all of them in one PR, and automate their finding in the future=) Thank you, we are closing this PR in favor of https://github.com/FuelLabs/fuel-core/pull/1554

You are welcome to join the mentioned PR and collaborate with the owner of this PR on the finalization of it.
