### ISSUE TITLE
Add ability to generate a snapshot folder

### ISSUE THREAD

**Issue by sarahschwartz** [FuelLabs/fuel-core#1933]
Right now if a developer wants to run a local node and fund their wallet, they must download or copy 4 different files to get the snapshot folder set up. It would save a lot of time and be a better experience if there was a command to generate this folder with toolchain-compatible configurations. Additionally, there should be prompts to input an address and base asset amount to make the process of funding a local wallet more straightforward.

**Comment by xgreenx** [comment]
It sounds like a feature that is better suited for `forc`. The `fuel-core` already provides a `StateConfig` type that `forc` team can use to create a snapshot for the user=)

**Comment by Voxelot** [comment]
Do we support any kind of default developer env with a cli flag like `--debug` or something similar? Might be a pretty simple thing to add that could save a lot of friction for new users.

**Comment by xgreenx** [comment]
We discussed many times in the past that `forc` can provide a wrapper around `fuel-core` that will simplify the usage. Like `forc node local` or `forc node run testnet`.

If we still plan to do that(and I think we need to do that), then `fork` is much better suited for it. `forc node local --fund base 0x123..89 10000000` looks very well. The `fuel-core` already provides all the required functionality to implement this behaviour.

**Comment by xgreenx** [comment]
Closing the issue for now until future communication=) Feel free to reopen it
