### ISSUE TITLE
Request for Turkish Translation of README 

### ISSUE THREAD

**Issue by Rumeyst** [FuelLabs/fuel-core#1935]
Hello,

I would like to request the creation of a Turkish version of the current English README. Providing a Turkish translation will help to make the project more accessible to Turkish-speaking users and contributors.

Proposed Solution:

1. Translate the entire README from English to Turkish.
2. Ensure that all technical terms are accurately translated or appropriately kept in English if they do not have a direct Turkish equivalent.
3. Add a link to the Turkish version at the top of the existing README for easy access.

## Context:

I am a Turkish speaker and would be happy to assist with or fully handle the translation process. Please let me know if this is something the project maintainers are open to, and if there are any specific guidelines or formats that I should follow.

Thank you for considering this request!

**Comment by xgreenx** [comment]
Hello, thank you for creating the issue.

I don't think that it is a good idea to have readme files for all different languages. Plus, the readme file itself contains simple English, so a browser translator should be sufficient enough.

But maybe you want to consider helping with our documentation portal. That is more broad and contains a lot of stuff that uses more advanced English.

Closing this issue for now.

**Comment by xgreenx** [comment]
https://github.com/FuelLabs/docs-hub
