### ISSUE TITLE
Translate documentation portal for local languages

### ISSUE THREAD

**Issue by cihatfe** [FuelLabs/fuel-core#1936]
I would lıke to contrıbute fuel ecosystem wıth translatıng offıcıal documents for local communıtıes. I can help wıth Englısh to Turkısh and Englısh to German as well as English to Kurdish. Feel free to reply me. I would lıke to help whatever I can as an official translator.

**Comment by xgreenx** [comment]
Please check the https://github.com/FuelLabs/fuel-core/issues/1935#issuecomment-2148074552. Closing for now as a duplicate
