### ISSUE TITLE
Fixin the error of wallet not install whe you try to bridge

### ISSUE THREAD

**Issue by rachidddon** [FuelLabs/fuel-core#1953]
![hhghghcmhfyh](https://github.com/FuelLabs/fuel-core/assets/116091587/24d9b646-f65f-429a-b70f-e38877e5f8ec)
 
am not the only one facing this problem, I tried clearing browser cash and I installed a new fuel wallet but still, this error shows up 8 of 10 times you try

**Comment by xgreenx** [comment]
Wallet is not related to `fuel-core` repository=) I would suggest to open the issue in the wallet repository=)
