### ISSUE TITLE
Optimize GraphQL "balances" query

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1965]
The source of this issue is https://github.com/FuelLabs/fuel-core/issues/623.

Initially, the idea was to remove all complex queries from `fuel-core` and make it part of the indexer's responsibility. But the SDK is deeply integrated with these basic queries, that we need to support them on `fuel-core`. For that, we need to optimize the following queries by aggregating some information in the off-chain worker or adding new indexes to the database:

- The `balance` and `balances` queries iterate over all entries of coins and messages in the storage. The off-chain worker should index the balance of each account and aggregate this information in a user-friendly form.
- ~The `coins_to_spend` query is very complex and requires `n^2` operations where `n` is the number of coins and messages. The algorithm itself can use additional indexes from RocksDB to solve the issue with dust coins and works fast.~
  - see [comment](https://github.com/FuelLabs/fuel-core/issues/1965#issuecomment-2435534571) 
- ~The `dry_run` already allows the dry running of many transactions; we just need to forbid several dry run sub-queries inside of one query.~
  - see [comment](https://github.com/FuelLabs/fuel-core/issues/1965#issuecomment-2435542866)

**Comment by rafal-ch** [comment]
https://github.com/FuelLabs/fuel-core/issues/2032#issuecomment-2382644669

**Comment by netrome** [comment]
> Initially, the idea was to remove all complex queries from fuel-core and make it part of the indexer's responsibility. But the SDK is deeply integrated with these basic queries, that we need to support them on fuel-core. 

Perhaps we should consider feature gating more complex queries so that node operators can choose to support them or not. This would allow node operators to opt for running a more lightweight node if they don't need to support these queries, and app developers can connect to nodes supporting the complex queries if they need them.

**Comment by netrome** [comment]
> Perhaps we should consider feature gating more complex queries so that node operators can choose to support them or not. This would allow node operators to opt for running a more lightweight node if they don't need to support these queries, and app developers can connect to nodes supporting the complex queries if they need them.

Oh I noticed we have an issue for this already https://github.com/FuelLabs/fuel-core/issues/1569

**Comment by rafal-ch** [comment]
The "coins to spend" issue was extracted into: https://github.com/FuelLabs/fuel-core/issues/2391

**Comment by rafal-ch** [comment]
The "dry run" issue was extracted into: https://github.com/FuelLabs/fuel-core/issues/2392
