### ISSUE TITLE
Add code owner and enhance approval process

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1982]

**Comment by netrome** [comment]
Discussed this in our retro. I'll have a look at it.

### Definition of done
We have a structure for defining code owners, and enforce at least one approval from a code owner for touched parts of the code. Initially @xgreenx, @Dentosal and @MitchTurner will be code owners for the entire repo, but the structure should support migrating to more code owners of more specific pieces of the code.
