### ISSUE TITLE
Remove use of `Option<BlockHeight>` as a query for blocks

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#2005]
There are a number of places we use `Option<BlockHeight>` to represent the block, where `None` is the genesis block. This is confusing, as it's implicit what `None` means without looking at the code.

Instead, we should introduce some type with the same cardinality, but with explicit names:

something like
```
enum BlockQuery {
    Specific(BlockHeight),
    Genesis,
}
```

**Comment by abdegenius** [comment]
Hey @MitchTurner i can work on this issue.. should i go ahead and take it up?!

**Comment by MitchTurner** [comment]
@abdegenius Hey! I believe that @matt-user has already dug into this [here](https://github.com/FuelLabs/fuel-core/pull/2033). It looks like it's still blocked on some reviews.

**Comment by abdegenius** [comment]
Oh ok then, let me know if it is still a problem so i can jump on it.
