### ISSUE TITLE
P2P is doing a lot of database lookups

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2023]
When we request transactions for the block, each transaction requires a separate lookup, which is very expensive, considering that transactions are randomly distributed throughout the database(because of randomness of `TxId`).

<img width="1657" alt="image" src="https://github.com/FuelLabs/fuel-core/assets/18346821/5c57b8dc-004a-4ceb-9b05-34b62c5fae14">

<img width="1667" alt="image" src="https://github.com/FuelLabs/fuel-core/assets/18346821/b280fd67-69d6-4acc-b452-a338b728f646">

**Comment by Voxelot** [comment]
Without changing the structure of the db to store full blocks instead of compact blocks, the most practical improvement with minimal changes would be to change this to a multi-get operation.

**Comment by AurelienFT** [comment]
I'm taking it as a side quest.

**Comment by rymnc** [comment]
Taking this up :)

**Comment by rymnc** [comment]
This is going to be partially solved with the caching layer in https://github.com/FuelLabs/fuel-core/pull/2352
