### ISSUE TITLE
Remove `GenericDatabase` in favor of using `StructuredStorage` everywhere

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#2027]
`GenericDatabase` is a wrapper around `StructuredStorage` and we probably don't need the distinction anymore.

**Comment by xgreenx** [comment]
We need `GenericDatabase` defined in the `fuel-core` because of the orphan rule=( So looks like we should keep it there, even if it fallbacks to the `StructuredStorage` implementation.
