### ISSUE TITLE
Add support for AWS KMS as a way to sign block in the `fuel-core`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2043]
## Overview

We need to add an ability to sign blocks with AWS KMS.

## Implementation details

Use [`aws-sdk-kms`](https://github.com/awslabs/aws-sdk-rust/tree/main/sdk/kms) crate for adding support for the PoA service to use AWS KMS to sign blocks.

It requires updating the CLI argument to pass a private key. It should be either a raw private key or credentials for KMS.

It would be nice to abstract the signing of the block via some trait and have different backed for signing. The sign function could be `async`.

## Testing details

Please check the https://fuellabs.slack.com/archives/C0298A7TT1C/p1720046999839619 thread for test credentials to test the change with a real cluster.

**Comment by Dentosal** [comment]
Open questions:
* Which signature algorithm we should use with KMS? It's not possible to use secp256k1 like we currently do, as [it's not on the list of supported algorithms](https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html#API_Sign_RequestSyntax)?
  * Given we have to use a different signature algo here, the blocks should probably which signature is used
* Should we allow passing in the configuration in any other way than just loading from the environment, i.e. with [`aws_config::load_from_env`](https://docs.rs/aws-config/latest/aws_config/fn.load_from_env.html)
  * Should we lock ourselves to a specific version of this config, or always use the latest availble defaults?
* Should we have this all behind an opt-out feature flag?
