### ISSUE TITLE
transactionsByOwner graphql query doesn't work properly when providing `last`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2044]
The next query return an empty response.

```query
query {
  transactionsByOwner(owner: "0x5502f46f90c3c68c85489b1f57ae6146c81e8549daf408574e3a9a0bb80c4ba0", last: 10) {
    nodes {
      id
    }
  }
}
```

We had the same problem in the past https://github.com/FuelLabs/fuel-core/issues/1040. But we should support it now. We need to investigate why it doesn't work.

**Comment by mmyyrroonn** [comment]
Hi @xgreenx, I'd like to take a look at this issue. Before starting my investigation, let me clarify the situation. In #1040, you mentioned that "we don't allow backward queries." Then, in #1492, "backward iteration" was supported. The expected behavior should be that when providing 'last', the query returns a non-empty result, similar to the case with 'first', but with a different ordering. Am I missing anything?

**Comment by xgreenx** [comment]
Hello, yes, you are correct=)

**Comment by AurelienFT** [comment]
After running multiple queries and tests I didn't found any issue. 
One example : 
- The query with first 10 : 
```
query {
  transactionsByOwner(owner: "0x6b63804cfbf9856e68e5b6e7aef238dc8311ec55bec04df774003a2c96e0418e", first: 10) {
    nodes {
      id
    }
  }
}
```
Result : 
```
{
  "data": {
    "transactionsByOwner": {
      "nodes": [
        {
          "id": "0xc1936a67fffecf035816f545af60ea5f3361e032df2c610d9f4a37f9c86839c8"
        },
        {
          "id": "0xd5c0eeb9fcabc4c6349baee6d75e06c3fe607488fb2377307446fcab4c9ddeea"
        },
        {
          "id": "0xe390430d0ba417504a292e0b1fff738159cfb93d454f2051ee1b1fd40836b572"
        },
        {
          "id": "0x34ab45d03adda5fb5ac4a94a54fa027cfb0f3decfb0c411dd9ab8297f800f774"
        },
        {
          "id": "0xab5b6bc8550fd16c41784b23122c591ef9785db05ad5f05a7be4bbdc8187cef2"
        },
        {
          "id": "0x19df7dbb700054f620147c3e27a63545ce8b6c627a6900cae56dfaf27ade7eb9"
        }
      ]
    }
  }
}
- The query with last 10 : 
```
query {
  transactionsByOwner(owner: "0x6b63804cfbf9856e68e5b6e7aef238dc8311ec55bec04df774003a2c96e0418e", last: 10) {
    nodes {
      id
    }
  }
}
```
Result : 
```
{
  "data": {
    "transactionsByOwner": {
      "nodes": [
        {
          "id": "0xc1936a67fffecf035816f545af60ea5f3361e032df2c610d9f4a37f9c86839c8"
        },
        {
          "id": "0xd5c0eeb9fcabc4c6349baee6d75e06c3fe607488fb2377307446fcab4c9ddeea"
        },
        {
          "id": "0xe390430d0ba417504a292e0b1fff738159cfb93d454f2051ee1b1fd40836b572"
        },
        {
          "id": "0x34ab45d03adda5fb5ac4a94a54fa027cfb0f3decfb0c411dd9ab8297f800f774"
        },
        {
          "id": "0xab5b6bc8550fd16c41784b23122c591ef9785db05ad5f05a7be4bbdc8187cef2"
        },
        {
          "id": "0x19df7dbb700054f620147c3e27a63545ce8b6c627a6900cae56dfaf27ade7eb9"
        }
      ]
    }
  }
}
```

Closing the issue. Feel free to re-open it with a reproductive example.

**Comment by AurelienFT** [comment]
Apparently the query fails on testnet, has I don't reproduce it locally, I unassign myself for now.

**Comment by xgreenx** [comment]
Another example:

```
query {
  transactionsByOwner(owner: "0xfc96a3a99ae1873e9e571a8be7d14111a2b4b7bd3abacb367c6e0f79c9c149d9", last: 10000) {
    nodes {
      id
      isBlob
      isCreate
      isScript
    }
  }
}
```

For https://mainnet.fuel.network/v1/graphql.
