### ISSUE TITLE
GraphQL `schema.sdl` out of date

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuel-core#2068]
We build TS types off the GraphQL Schema file, which we then use for our chain config. Blob transactions require a `v4` gas cost version config. The schema currently only allows `v1`. I believe it comes from [this file](https://github.com/FuelLabs/fuel-core/blob/6758990fa9bbe8e892947f0bb21fbcbfe9c081eb/crates/client/assets/schema.sdl#L465). It would be great to get this updated so we can again have end to end, validated type support with the spec.

**Comment by xgreenx** [comment]
The scheme has version 1 intentionally. GraphQL types don't need to use the same versioning as Rust types. We will increase the version when we bring a breaking change into it.
