### ISSUE TITLE
Add `nodeAndChainInfo` endpoint that combines `nodeInfo` and `chain` queries

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuel-core#2083]
The TS SDK currently sends `nodeInfo` and `chain` queries separately on every `Provider` instantiation. Combining them in one endpoint seems like a quick win for reducing the amount of requests.

**Comment by netrome** [comment]
Picking this up now

**Comment by netrome** [comment]
Alright, I need to understand this better before I can do a sensible implementation. @nedsalk can you explain why you need a separate endpoint, and why you can't simply combine the queries on your end to a single query?

For example, this is a single query that fetches both information from the `nodeInfo` endpoint and the `chain` endpoint:

```
query {
  chain {
    latestBlock {
      id
      version
    }
  }
  nodeInfo {
    nodeVersion
  }
}
```

which would give you a response of this form:

```
{
  "data": {
    "chain": {
      "latestBlock": {
        "id": "0xc8e6d82d0fb28881b21a3d10b70cc2532b1bba142854e37910910a53cc8f365b",
        "version": "V1"
      }
    },
    "nodeInfo": {
      "nodeVersion": "0.33.0"
    }
  }
}
```

**Comment by nedsalk** [comment]
@netrome never really thought about it :man_facepalming: Thanks, that's a solution as well :smile:

**Comment by netrome** [comment]
> @netrome never really thought about it 🤦‍♂️ Thanks, that's a solution as well 😄

Wonderful, happy coding!
