### ISSUE TITLE
We are using `Instant::now()` and `Tai64::now()` directly in the block producer, rather than having some time interface

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#2091]
Time is unreliable IO. We should be able to isolate an manipulate it using a fake/mock rather than being dependent on the system clock.
```rs
    fn extract_block_info(last_block: &BlockHeader) -> (BlockHeight, Tai64, Instant) {
        let last_timestamp = last_block.time();
        let duration_since_last_block =
            Duration::from_secs(Tai64::now().0.saturating_sub(last_timestamp.0));
        let last_block_created = Instant::now()
            .checked_sub(duration_since_last_block)
            .unwrap_or(Instant::now());
        let last_height = *last_block.height();
        (last_height, last_timestamp, last_block_created)
    }
 ```

**Comment by MitchTurner** [comment]
It seems like we have introduced unnecessary complexity into the code to accommodate manual block production, where we should be able to just advance fake time in our tests.

**Comment by netrome** [comment]
Note, the provided code snippet is from the PoA consensus provider (`crates/services/consensus_module/poa/src/service.rs`) and not the block producer `crates/services/producer/src/block_producer.rs`. The block producer only seems to have this problem for the `dry_run` functionality, and takes the time as input in all other cases, so I will focus on doing this for the consensus provider.
