### ISSUE TITLE
RocksDB Opens too many descriptors by default

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2093]
The RocksDB opens a lot of files for its work. Currently, we open an unlimited number of files that could hit at some point 2M descriptors.

Not all machines have huge descriptor limits by default. To avoid errors on the user's side, we could set the limit for open files based on OS limit. 

Let's say the limit on the OS is `X`. Then, we could use `X/2` as a limit for the RocksDB.

Also, we need to update the Readme file to highlight that property and that low descriptors limit could decrease performance.

**Comment by mvares** [comment]
@xgreenx, where can I the limit of a OS?

**Comment by MitchTurner** [comment]
We could add a cli flag that would allow the user to control this behavior. i.e. if it's set it uses the specified value, if it's not set it uses system limit.
