### ISSUE TITLE
Add more graceful handling of the huge number of transactions during production

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2114]
The total number of allowed transactions per block is `65535` due to the `TxPointer` limitations.

Our current network configuration handles it.

But since we plan to have many custom rollups that use `fuel-core`. It would be nice to add more graceful handling of a huge number of transitions.

We have several places where we need to handle it:
- Executor fetches transactions from the `TxPool` based on the remaining gas. We need to also take into account the remaining number of transaction slots. Note: FTI transactions also occupy slots.
- When the block producer increases DA height, only gas used by FTI is taken into account. We also need to be sure that all transactions can fit into one block.
- Maybe increase the minimal gas on the L1 side to be more than `1` https://github.com/FuelLabs/fuel-bridge/pull/215/files#diff-cf9b39d4822d2f60928e44960317ad86812ccf644704cfdd364279ba02e673acR10. Maybe `10_000` is not bad as a default value.

**Comment by acerone85** [comment]
I'll start working on this one, will probably add more comments with questions to get context

**Comment by acerone85** [comment]
What is the expected way this should be handled? Should we have a consensus parameter that mentions the maximum number of transactions per block (in which case this is related to what @rafal-ch is doing with [#2133](https://github.com/FuelLabs/fuel-core/issues/2133))? Or is there any other approach we can take?

**Comment by acerone85** [comment]
What is a FTI transaction?

**Comment by xgreenx** [comment]
FTI - Force transaction inclusion. You can submit the transaction to L1 instead of L2(maybe someone censorships your transaction), and it will be included when the block producer increases the DA block height. FTI - is a regular transaction that just comes from L1, instead of TxPool.

**Comment by acerone85** [comment]
Reopening, Still need to update the maximal gas price
