### ISSUE TITLE
Fetch L1 data from different RPC providers

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2118]
To resolve the https://github.com/FuelLabs/security-drills/issues/10, we need to create a service that can fetch L1 data from different sources.

The service should compare results from different sources and return an error if 51% can't be reached.

## Implementation details

The service should be independent and reusable. We should be able to use this service in the `fuel-core`, and we should be able to create a separate binary that uses this single service that implements the required methods of the Ethereum RPC.

**Comment by xgreenx** [comment]
> A simpler option could be to use the QuorumProvider in ethers-rs
https://docs.rs/ethers/latest/ethers/providers/struct.QuorumProvider.html

**Comment by AurelienFT** [comment]
As a first part of this issue, #2122 is changing the behaviour of the relayer to allow multiple URI and will accept the result of an RPC call only if 50% providers or more gives the same answer.

The next step would be to have a separate project that could be run as a service along with the core, block-committer, etc... that will implement this multiple RPC logic.
