### ISSUE TITLE
`TransactionScript` Fails with `OutOfGas` But It Is Introduced Into Latest Block

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuel-core#2143]
Steps to reproduce:

1 - Starting `fuel-core` with:

`fuel-core run --vm-backtrace --utxo-validation --debug`

2 - Submitting a simple transfer `TransactionScript`, with `maxFee` and `scriptGasLimit` set to `0`, like this one

https://gist.github.com/Torres-ssf/35975e9d6e89cd594e430fe4e64cd962

Fuel-core will throw the error `OutOfGas` for the given transaction. Despite this error, the transaction is still introduced into the latest block.

As a result, the recipient unexpectedly receives the transferred amount, indicating that the transaction was processed even after the error was raised.

**Comment by xgreenx** [comment]
Could you please provide a runnable example of the script?

**Comment by Torres-ssf** [comment]
@xgreenx https://github.com/Torres-ssf/transfer-error

**Comment by Torres-ssf** [comment]
I'm closing this issue as it was due to a misunderstanding on my part.

I initially thought that `OutputCoin` would only be generated if the transaction succeeded. 

However, I've realized that even if the transaction fails, the `OutputCoin`(s) are still generated.
