### ISSUE TITLE
Add all mechanisms needed for the API to connect to TXPoolV2

### ISSUE THREAD

**Issue by AurelienFT** [FuelLabs/fuel-core#2185]
TxPool V2 only has this PR for now : https://github.com/FuelLabs/fuel-core/pull/2162. This PR includes everything needed for the pool to store, check collision and select blocks.

However a lot of machinery is needed for the pool to be connected to others services. This issue covers the addition for the pool to work with the API.

The API should be able to get the status from the `insert` method that doesn't return anything anymore

It will also be a good time to revisit the error type and their description to be more useful for API user.

**Comment by xgreenx** [comment]
Done in https://github.com/FuelLabs/fuel-core/pull/2263
