### ISSUE TITLE
Allow insertion of transactions in the TxPool v2

### ISSUE THREAD

**Issue by AurelienFT** [FuelLabs/fuel-core#2186]
Currently, in the TxPool V2 you can only insert `PoolTransaction`. We need to instantiate the workflow to pass from `Transaction` to `PoolTransaction`. In fact it already exists in the `transaction_conversion.rs` file but it's a copy paste from the previous TxPool and used in tests only for now.

We want to change the behavior to verify in this order : 

- Basic verification (max_gas, max_size, ...)
- Input verification (exists on pool or db if `utxo_validation` is asked)
- Verify predicate, wasm
- Include in the pool (which implies a new verification of the inputs)

@xgreenx can you confirm me the order ?

It will also be a great time to instantiate more tests and standardize them all.
Better type for the insert result in the pool

**Comment by xgreenx** [comment]
Yeah, the order it right=)
