### ISSUE TITLE
Add safety on maximum size of caches in TxPool

### ISSUE THREAD

**Issue by AurelienFT** [FuelLabs/fuel-core#2191]
How long is the `GraphStorage` expected to live? If this is for the lifetime of the app we maybe want to consider putting an upper bound on the number of entries we can store in the caches? If for any reason (like a bug or malicious behavior) we are not able to properly clear the caches, we might go OOM.

_Originally posted by @rafal-ch in https://github.com/FuelLabs/fuel-core/pull/2162#discussion_r1756318500_

**Comment by xgreenx** [comment]
Looks like it is done by gas and size limit of the TxPool
