### ISSUE TITLE
Add specific tests for each module in the TxPool v2

### ISSUE THREAD

**Issue by AurelienFT** [FuelLabs/fuel-core#2196]

**Comment by AurelienFT** [comment]
https://github.com/FuelLabs/fuel-core/pull/2216/#discussion_r1790901668

**Comment by rafal-ch** [comment]
https://github.com/FuelLabs/fuel-core/pull/2216#discussion_r1790901668

**Comment by AurelienFT** [comment]
Ty

**Comment by AurelienFT** [comment]
Done in #2327
