### ISSUE TITLE
Add forward compatibility test for `fuel-core 0.36.0`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2198]
After release of `fuel-core 0.36.0` we need to add forward compatibility test for it.

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/63f0e447-81c9-4935-abd7-2b32f5f63422">

**Comment by acerone85** [comment]
I'm happy to have a look at this one after 0.36.0 is released

**Comment by rafal-ch** [comment]
Closed with https://github.com/FuelLabs/fuel-core/pull/2271
