### ISSUE TITLE
Improve gas price analysis tool to have parameterized DA finalization time

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-core#2218]
The simulation in the analysis tool is hard-coded to update DA every 12 blocks. This doesn't represent reality. In production we can expect DA block finalization to be something like 3 mins? Maybe?

We should modify this code to allow the user to configure this value and compare results.

**Comment by Voxelot** [comment]
finalization time on ethereum is ~15 mins by the most conservative measures
