### ISSUE TITLE
Failing test - DNS multiaddr resolution

### ISSUE THREAD

**Issue by acerone85** [FuelLabs/fuel-core#2221]
When running `source ci_checks.sh`

```
---- dnsaddr_resolution::tests::dns_resolver__parses_all_multiaddresses_from_mainnet_dnsaddr_entry stdout ----
thread 'dnsaddr_resolution::tests::dns_resolver__parses_all_multiaddresses_from_mainnet_dnsaddr_entry' panicked at crates/services/p2p/src/dnsaddr_resolution.rs:101:14:
called `Result::unwrap()` on an `Err` value: no record found for Query { name: Name("_dnsaddr.core-test.fuellabs.net.local."), query_type: TXT, query_class: IN, mdns_unicast_response: false }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rymnc** [comment]
that's interesting, why is the `.local.` getting appended for you when we make the call to `core-test.fuellabs.net` ?
perhaps something in your `/etc/hosts/` file?

**Comment by acerone85** [comment]
ok, I run some scenarios:
VPN disabled, no . at the end: test passes
VPN enabled, no . at the end: test errs with  called Result::unwrap() on an Err value: no record found for Query { name: Name("_[dnsaddr.core-test.fuellabs.net](http://dnsaddr.core-test.fuellabs.net/).local."), query_type: TXT, query_class: IN, mdns_unicast_response: false }
VPN disabled, with . at the end: test passes
VPN enabled, with . at the end: test errs with called Result::unwrap() on an Err value: request timed out
I guess nordVPN is tunnelling dns requests to their servers, and the app does not provide many functionalities to set split-tunneling :disappointed:
