### ISSUE TITLE
Introduce Limiter abstraction for Executor parameters

### ISSUE THREAD

**Issue by acerone85** [FuelLabs/fuel-core#2234]
Maybe we can take this opportunity and rename this to `transaction_count_limit`. 

I know it was merged like that in [this PR](https://github.com/FuelLabs/fuel-core/pull/2182), but [this one](https://github.com/FuelLabs/fuel-core/pull/2195) will soon bring yet another similar name. Having such generic name as `transactions_limit` could be confusing.

Also, we might consider introducing a "limiter" abstraction in a follow-up ticket, instead of having three separate params.

_Originally posted by @rafal-ch in https://github.com/FuelLabs/fuel-core/pull/2189#discussion_r1768474551_

**Comment by xgreenx** [comment]
We still need separate parameters for WASM interface, so I think we don't need to change it=)
