### ISSUE TITLE
Adjust GraphQL complexity for block query

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2273]
We want to allow up to 50 full blocks per blocks request. It is around `50 * 128 kb = 6.25 MB` plus receipts and transaction status.

We need to adjust GraphQL complexity price to allow that within 20k limit( the `transactions` field is too expensive). Or maybe increase default complexity but still take into accounts other queries.

**Comment by Namanedogawa** [comment]
I’d like to propose changes to allow up to 50 full blocks per request while adjusting the GraphQL complexity to stay within the 20k limit.

Suggested Code Changes:
In src/resolvers.rs, please consider:

const MAX_BLOCKS: usize = 50; // Allow up to 50 blocks
const MAX_COMPLEXITY: usize = 20000; // Set max complexity

pub fn resolve_blocks(args: &BlockQueryArgs) -> Result<Vec<Block>, GraphQLError> {
    if args.blocks.len() > MAX_BLOCKS {
        return Err(GraphQLError::new("Cannot request more than 50 blocks."));
    }

    let complexity = calculate_complexity(&args);
    if complexity > MAX_COMPLEXITY {
        return Err(GraphQLError::new("Query complexity exceeds the limit."));
    }

    if args.blocks.len() > 20 && args.include_transactions {
        return Err(GraphQLError::new("Cannot include transactions for more than 20 blocks."));
    }

    // Existing request logic...
}

This change improves API usability without sacrificing performance. I look forward to your feedback .

**Comment by Namanedogawa** [comment]
I'd like to propose changes to allow up to 50 full blocks per request while adjusting the GraphQL complexity to stay within the 20k limit.

**Suggested Code Changes:**
In `src/resolvers.rs`, please consider:

```rust
const MAX_BLOCKS: usize = 50; // Allow up to 50 blocks
const MAX_COMPLEXITY: usize = 20000; // Set max complexity

pub fn resolve_blocks(args: &BlockQueryArgs) -> Result<Vec<Block>, GraphQLError> {
    if args.blocks.len() > MAX_BLOCKS {
        return Err(GraphQLError::new("Cannot request more than 50 blocks."));
    }

    let complexity = calculate_complexity(&args);
    if complexity > MAX_COMPLEXITY {
        return Err(GraphQLError::new("Query complexity exceeds the limit."));
    }
    
    if args.blocks.len() > 20 && args.include_transactions {
        return Err(GraphQLError::new("Cannot include transactions for more than 20 blocks."));
    }

    // Existing request logic...
}

This change improves API usability without sacrificing performance. I look forward to your feedback .
