### ISSUE TITLE
Add metrics for the graphql complexity

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2274]
Track the complexity of each query in the histogram divided by 1k, 5k, 10k, 20k, 50k, 100k, 250k, 500k, 1M, 5M, 10M

**Comment by tusharnagar17** [comment]
Hi @xgreenx,
I would like to work on this. 
Would appreciate any clarification or guidance you can provide ?

**Comment by AurelienFT** [comment]
Done in #2349
