### ISSUE TITLE
Fuzz tests and benches on TxPoolv2

### ISSUE THREAD

**Issue by AurelienFT** [FuelLabs/fuel-core#2281]
Do we have any plans of running a real fuzzer on this? Perhaps we should consider creating a follow-up to do so.

_Originally posted by @netrome in https://github.com/FuelLabs/fuel-core/pull/2162#discussion_r1785894358_

Issue to elaborate

**Comment by netrome** [comment]
Thanks for opening! Seems like this is not trivial though and a low prio so let's close this for now https://github.com/FuelLabs/fuel-core/pull/2162#discussion_r1785925767
