### ISSUE TITLE
chore(gas_price_service): add new configuration fields to `GasPriceServiceConfig`

### ISSUE THREAD

**Issue by rymnc** [FuelLabs/fuel-core#2287]
`v1` of the `gas-price-algorithm` requires a few new parameters to construct it

https://github.com/FuelLabs/fuel-core/blob/c039c28b3a2707dbef69e9d21d87673a9e0bbf38/crates/fuel-gas-price-algorithm/src/v1.rs#L105-L157

we need to modify CLI args to contain them, as well as update `Config`: https://github.com/FuelLabs/fuel-core/blob/2caca6145044bef4c92f6c64d8b5731545a4514a/crates/fuel-core/src/service/config.rs#L38-L76

cc: @MitchTurner to confirm which fields can be omitted on first startup

## Definition of done

- [ ] `fuel-core` Config contains everything required by the `GasPriceAlgorithmV1`

**Comment by MitchTurner** [comment]
Should be done now.
