### ISSUE TITLE
It is not possible to request the salt of the genesis contract

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2296]
## Problem

Requesting salt of the genesis contracts fails because we forgot to update salt table and store this information. We need to add handling of it on the `fuel-core` side. 

Run next query on the testnet:

```
query {
  contract(id: "0x7e2becd64cd598da59b4d1064b711661898656c6b1f4918a787156b8965dc83c") {
    id
    salt
    bytecode
  }
}
```

## Definition of done

The query shouldn't fail for the testnet and any network.
The genesis process should also index contracts in the off chain database. Not only coins and messages.

**Comment by rymnc** [comment]
what should the salt be for the `genesis_contract`? zero?

**Comment by xgreenx** [comment]
Yep

**Comment by netrome** [comment]
@rymnc to create follow-up issue about figuring out the proper way to handle similar situations in the future.

**Comment by MitchTurner** [comment]
Looks like this was solved.
