### ISSUE TITLE
Limit number of concurrent queries the GraphQL service

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2303]
## Definition of done:

The number of queries in GraphQL service is limited.

**Comment by netrome** [comment]
I think we can achieve this directly at the http layer with just this change
![image](https://github.com/user-attachments/assets/429e96c9-e5c0-4825-9cc9-4a8424438a42)

I'll double check that this gives the intended behavior and add a configuration option for this.

**Comment by netrome** [comment]
Okay, so `http2_max_concurrent_streams` limits the amount of HTTP2 streams per connection, but doesn't seem to prevent multiple connections to be established.

We can limit the number of connections by using a concurrency limit layer with Tower: https://docs.rs/tower/0.5.1/tower/limit/concurrency/struct.ConcurrencyLimitLayer.html

**Comment by netrome** [comment]
Alright, we use `axum = 0.5` without any additional features so HTTP2 isn't enabled. So it seems like we don't have to worry about concurrent HTTP2 streams. The Tower middleware seems like the way to go. I'm proceeding in that direction.

**Comment by netrome** [comment]
Draft PR up: https://github.com/FuelLabs/fuel-core/pull/2309
I'll add tests to it before marking the PR as ready.
