### ISSUE TITLE
`/health` endpoint maybe be queued causing false positive restart for operators

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2319]
The `/health` endpoint now is also limited by concurrency limit after https://github.com/FuelLabs/fuel-core/pull/2309

<img width="517" alt="image" src="https://github.com/user-attachments/assets/168245dc-563a-4075-b7f7-fd0ac748de17">

If the node has a lot of queries it can be terminated by failing liveness check for node operators.

**Comment by Voxelot** [comment]
We should only apply the concurrency limit on the graphql schema route if possible
