### ISSUE TITLE
feat(storage_consistency): define safe method to introduce data at genesis height

### ISSUE THREAD

**Issue by rymnc** [FuelLabs/fuel-core#2329]
## Context

In https://github.com/FuelLabs/fuel-core/pull/2322 we introduced a method to rewrite some data at genesis height for the `ContractsInfo` table. This was done by using an unsafe operation to convert a database into its genesis stage, and writing to it then.

We need to think and rework how we do this in the future in a reliable way without the unsafe operation.

## Definition of Done
- [ ] We can load data that was missed in the initial genesis snapshot at a later date to the genesis height of various tables without unsafely converting their stage.

**Comment by xgreenx** [comment]
We removed this method in the same PR=)
