### ISSUE TITLE
Maybe `fuel-core` block producer uses incorrect TAI time

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#2338]
The library that we are using doing `(10 + (1 << 62))`, while wikipedia says `(37 + (1 << 62))`. We need to investigate this question

<img width="872" alt="image" src="https://github.com/user-attachments/assets/91a3770b-c044-42b7-afbf-a1987ac351a2">

**Comment by rymnc** [comment]
https://github.com/RustCrypto/formats/issues/675

**Comment by AurelienFT** [comment]
PR on Tai crate : https://github.com/RustCrypto/formats/pull/1583
