### ISSUE TITLE
Optimize GraphQL "dry run" query

### ISSUE THREAD

**Issue by rafal-ch** [FuelLabs/fuel-core#2392]
The source of this issue is https://github.com/FuelLabs/fuel-core/issues/623.

Initially, the idea was to remove all complex queries from `fuel-core` and make it part of the indexer's responsibility. But the SDK is deeply integrated with these basic queries, that we need to support them on `fuel-core`. For that, we need to optimize the following query by aggregating some information in the off-chain worker or adding new indexes to the database:

- The `dry_run` already allows the dry running of many transactions; we just need to forbid several dry run sub-queries inside of one query.

Extracted from the https://github.com/FuelLabs/fuel-core/issues/1965, which initially covered optimizations for 3 different areas: balances, coins to spend, dry run.

**Comment by xgreenx** [comment]
It already was done with introduction of the complexity=)
