### ISSUE TITLE
Claimable rewards are always zero after staking serveral days

### ISSUE THREAD

**Issue by threewebcode** [FuelLabs/fuel-core#2521]
![staking](https://github.com/user-attachments/assets/9dcb15b7-de56-4ed4-8dbb-630a44fd2520)

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Fuel SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by xgreenx** [comment]
ThThank you for creating an issue. This repository is related to the `fuel-core` and not related to the UI.

If you have questions on how staking works, you can ask them on the Discord channel.

I'm losing the issue for now since it is not the right place for it.

**Comment by threewebcode** [comment]
> ThThank you for creating an issue. This repository is related to the `fuel-core` and not related to the UI.
> 
> If you have questions on how staking works, you can ask them on the Discord channel.
> 
> I'm losing the issue for now since it is not the right place for it.

Which repository should this issue be posted?

**Comment by Jason-Tariq** [comment]
Hello @threewebcode  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
