### ISSUE TITLE
replace usage of surf with lighter-weight http-client

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#287]
surf is bloated with an unmaintained dependency graph containing many security warnings. We should replace it with a lighter-weight solution such as reqwest or hyper.

It should also use rustls or some other non-openssl dependency.

**Comment by Voxelot** [comment]
We can't migrate to reqwest since openssl dependencies are being enabled by the graphql client extension framework cynic. Once they release this pr (https://github.com/obmarg/cynic/pull/411), we'll be able to use reqwest without depending on openssl.

**Comment by adlerjohn** [comment]
@Voxelot Cynic seems to be taking its sweet time releasing v2. Would it be worth it to fork it and release a forked cynic we can use ourselves?

**Comment by Voxelot** [comment]
Cynic is composed of many libraries, so an alternative is to only use its [querygen](https://github.com/obmarg/cynic/tree/master/cynic-querygen) crate, and wrap it with our own HTTP client.

**Comment by adlerjohn** [comment]
Note: https://github.com/http-rs/http-client/issues/98

**Comment by xgreenx** [comment]
@Voxelot I guess we can close this issue because of https://github.com/FuelLabs/fuel-core/pull/786 ?

**Comment by Voxelot** [comment]
yep!
