### ISSUE TITLE
Separate cert-manager from fuel-core ingress management

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#303]
Currently, destroying any fuel-core ingress also removes cert-manager from the k8s cluster. This doesn't work well when we have multiple fuel-core environments in the sharing the same cluster, as this will clobber a shared resource between independent environments (including monitoring).

Cert manager setup and teardown should be potentially done as part of create-k8s.sh and delete-k8s.sh instead of fuel-core-ingress-deploy/delete.sh. This is because it's setup at the k8s cluster level, rather than deployment env level.

**Comment by rfuelsh** [comment]
@Voxelot - 

1) Sure I agree with that- we would need to separate cert-manager and ingress deployment which I can work

2) the create-k8s.sh and delete-k8s.sh deploy terraform based code and it takes time to deploy the terraform code (this cannot be timed - its different for each environment), so its better to deploy helm charts (cert manager, etc.) in separate scripts from terraform code hence a different then the create-k8s.sh and delete-k8s.sh scripts 

This fix in separate scripts I can work on.
