### ISSUE TITLE
Issue installing `fuel-core` and a temporary solution

### ISSUE THREAD

**Issue by dabit3** [FuelLabs/fuel-core#351]
when running:

```
cargo install fuel-core
```

I'm running into this issue:

```
  Installing fuel-core v0.7.0
error: failed to compile `fuel-core v0.7.0`, intermediate artifacts can be found at `/var/folders/k3/k6wg86gs3n79388pg_4tf14c0000gn/T/cargo-installk2BlAh`

Caused by:
  failed to select a version for the requirement `fuel-asm = "^0.5"`
  candidate versions found which didn't match: 0.4.0, 0.3.0, 0.2.0, ...
  location searched: crates.io index
  required by package `fuel-core v0.7.0`
```

By downgrading to an earlier version I'm able to install:

```sh
cargo install fuel-core --version ^0.6
```

Running on M1 MacOS 11.2.3

**Comment by ControlCplusControlV** [comment]
Can you provide insight on your toolchain? Things like `rustc` and `cargo` versions would be helpful. (Commands are `rustc --version` and `cargo --version`). I am unable to recreate with

```
cargo 1.61.0 (a028ae42f 2022-04-29)
rustc 1.61.0 (fe5b13d68 2022-05-18)
rustup 1.24.3 (ce5817a94 2021-05-31)
```
on an M1 Mac with MacOS 12.3.1

[Fuel-asm](https://crates.io/crates/fuel-asm) has a 0.5.1 release, so this error points to an out of date package repository

**Comment by Voxelot** [comment]
@dabit3 have you already asked for support on discord? Repo-level issues are mainly for bugs or feature work. This sounds like a local developer environment issue, since `cargo publish` prevents us from publishing a crate with missing deps.

**Comment by adlerjohn** [comment]
(For posterity: fuel-core `v0.7.0` requires Rust >=`1.60.0`.)

**Comment by dabit3** [comment]
Thanks for the help here, looks like I needed to update to a newer version of Rust, will take these types of questions into Discord in the future.
