### ISSUE TITLE
Have ability to get validator set by da_height that is drifted to past  

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-core#365]
Currently, our validator set represents the last finalised block and that is okay as mechanisms inside `fuel-core` require only a set that is the newest. The problem is that the requested set depends on da_height found inside the block header and that height is going to be different from the current finalised set and mostly drift to some past height.

Have the ability to respond with validator set in the near past, this means removing/adding validator set consensus keys and removing/adding stake depending on diff between the current finalized block and the requested height.

**Comment by adlerjohn** [comment]
Since the active validator set will only be ~100 validators each time...could the entire validator set just be stored every time it changes?

**Comment by rakita** [comment]
There is already a mechanism done that saved diff on every eth block, and I do that to apply forward diff, so i just need to leverage that and do reverse. 

Additionally, there is a validator delegations stake that I need to know so that when undelegation happens I need to fetch the old delegation and remove that stake from validators.

**Comment by rakita** [comment]
This is the next thing that I will do, it is not a big task but i didn't want to bundle it with that big relayer pull request.
