### ISSUE TITLE
Refactor all graphql pagination using iter_all into common code

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#382]
Currently each paginated api which uses the database iter_all is reimplementing lots of similar pieces of code. This make consistency in pagination behavior inconsistent, and harder to test. 

The interface should accept all the common pagination params (first, last, before, after), the database column to iterator over, and accept a closure to map db results into grapqhl schema types.

**Comment by ControlCplusControlV** [comment]
Should also note that these tests should utilize the new [rstest](https://docs.rs/rstest/latest/rstest/) which is currently(?) used on the `contract.rs` test

**Comment by xgreenx** [comment]
Fixed in the https://github.com/FuelLabs/fuel-core/pull/834
