### ISSUE TITLE
Fuel block producer

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-core#388]
It calls `fuel-block-executor` to create next block and `fuel-txpool` to get a list of transactions. 
It is called by `fuel-core-bft` to create the new pending block.

Database trait for producer needs to be made similar to Relayer and VM.

It needs to have this functionality: https://github.com/FuelLabs/fuel-core/wiki/Interfaces-between-fuel-client-modules#blockproducer-channels

**Comment by Voxelot** [comment]
closes #50 

Linking the issue for reference since block producer is the component we actually intend to build which will enable multi-tx blocks.

**Comment by Voxelot** [comment]
related: https://github.com/FuelLabs/fuel-core/pull/409
