### ISSUE TITLE
Fuel core bft

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-core#389]
It needs to bind `fuel-bft` with the rest of `fuel-core` modules

I think we still didn't include the change that we talked about at devconnect  into the channel structure: https://github.com/FuelLabs/fuel-core/wiki/Interfaces-between-fuel-client-modules#bft-channels

It needs to define the trait for the database similar to Relayer and VM.

**Comment by Voxelot** [comment]
Ah right, Victor had taken those notes. Mind adding them to the wiki @vlopes11?

**Comment by Voxelot** [comment]
> It needs to define the trait for the database similar to Relayer and VM.

We may not need the trait, since the interfaces for storage are already likely defined in the fuel-bft repo. This is just a module to implement those interfaces.

**Comment by xgreenx** [comment]
We decided to move step by step and implement only the functionality we plan to use now or soon. We don't have the actual description of how `fuel-core-bft` will work, and it is excluded from `fuel-core` dependencies right now. We can close this issue for now and create it one more time when the time comes.
