### ISSUE TITLE
Relayer - decouple finalized event processing from eth pubsub

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#398]
While using the eth pubsub apis for pending events provides useful ux for users tracking deposits or withdrawals, or for validators to track pending block commitments, they should be considered unreliable for sourcing finalized events for consensus critical functions.

This is because ethereum provides zero durability guarantees for their pubsub APIs and no way to replay missed messages. This will be problematic on many levels, for example if there are network disruptions, if the eth client pubsub connection drops, or the eth node reboots / rescales. 

Instead relying on pubsub messages for our source of truth, we should do the following:

1. Make the finalized event handler responsible for its own log/block polling without pubsub, using only finalized blocks it cares about.
2. Pending events will continue to make a best effort to track pending activity, but will wait to be notified by the finalized event handler when an event was processed before removing it.

Inverting the dependency between the pending events and finalized events will simplify the relayer design. It gives us rock-solid guarantees that no log entry was dropped or accidentally processed multiple times in a way that could affect consensus. The handling of pending events can also be greatly relaxed, as pubsub data would be relegated to UX/UI concerns and doesn't need to be perfectly accurate all the time. 

For example, we'd no longer need to be concerned about the precise handling of subscriptions being started or stopped at the perfect time [during initialization](https://github.com/FuelLabs/fuel-core/pull/345#discussion_r889402006), and performing [sanity checks](https://github.com/FuelLabs/fuel-core/blob/feac06c7f883cbba91df6df1dc05520f878a4ebc/fuel-relayer/src/finalization_queue.rs#L259) on all the data we receive from the pubsub system before committing it.

**Comment by xgreenx** [comment]
It is done in the https://github.com/FuelLabs/fuel-core/pull/631
