### ISSUE TITLE
Bridge requirements

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-core#401]
There are a lot of small things to be added so that bridge can function properly. They are mostly relayed to new MessageOutput and MessageInput.
- [x] fuel-tx Add new message inputs and outputs specified at: https://github.com/FuelLabs/fuel-specs/pull/318/files
  - [x] fuel-types: https://github.com/FuelLabs/fuel-types/pull/38
  - [x] fuel_tx: https://github.com/FuelLabs/fuel-tx/pull/149
- [x] fuel-vm: 
  - [x] add support for new input and include the amount from `InputMessage` as a base asset 
  - [x] fuel-vm: add support for Send message to output (SMO) instruction:
 https://github.com/FuelLabs/fuel-vm/issues/141
  - [x] integrate inside fuel-core.
- [x] fuel-relayer integration:
  - [x] still can not be published bcs of ethers-rs. https://github.com/FuelLabs/fuel-core/pull/410
  - [x] include module configuration: https://github.com/FuelLabs/fuel-core/pull/440
  - [x] https://github.com/FuelLabs/fuel-core/issues/447 
  - [x] https://github.com/FuelLabs/fuel-core/issues/454
  - [x] Support da message in fuel-relayer: https://github.com/FuelLabs/fuel-core/issues/476
  - [x] #520
- [x] #521
- [ ] fuel-executor: iterate over all not reverted transactions and get all MessageOutputs, set their nonce and create Merkle tree for block header. Add MessageRoot to the header.

**Comment by rakita** [comment]
@vlopes11 this are message related tasks

**Comment by Voxelot** [comment]
closing as this is basically done, follow-up tasks can be tracked separately.
