### ISSUE TITLE
Setup Fuel-Core Jaeger Traces

### ISSUE THREAD

**Issue by rfuelsh** [FuelLabs/fuel-core#406]
We need to use the new jaeger implementation and setup traces for fuel-core using Opentelemetry SDK- https://opentelemetry.io/docs/instrumentation/rust/#:~:text=A%20language%2Dspecific%20implementation%20of,metrics%2C%20logs%2C%20and%20traces.

**Comment by xgreenx** [comment]
@Voxelot I added this issue to `Beta 4` not to forget to discuss it. Because it is related to our plans regarding telemetry

**Comment by xgreenx** [comment]
@Voxelot Do we need it? Closing for now, unless you think it is something that we need
