### ISSUE TITLE
Improve correctness of graphql pagination arg validation

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-core#415]
The [Balances API](https://github.com/FuelLabs/fuel-core/blob/master/fuel-core/src/schema/balance.rs#L137) doesn't implement proper pagination checks, and should have a snippet added like the one in the[ contracts API](https://github.com/FuelLabs/fuel-core/blob/master/fuel-core/src/schema/contract.rs#L156) to ensure the right argument combination is included.

Planning on getting this when I tackle #382, but wanted to document this error exists

**Comment by Voxelot** [comment]
This most likely applies to all pagination apis implemented before the contract api
