### ISSUE TITLE
setup ci action to simulate publishes

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#418]
Troubleshooting CI failures during publish is difficult, as there is no way to test publishing without actually make a real publish.

We should have a custom action that allows us to simulate all the actions of a publish before officially tagging the release.

- allow user to set a custom publish tag via action input instead of creating a real tag
- use an ephemeral crate registry during the publish process
  - override the default registry for any dependencies between workspace members to use local registry
- skip docker image upload
- skip binary artifact upload

**Comment by adlerjohn** [comment]
> use an ephemeral crate registry during the publish process

This is interesting. Would it be possible host an instance of crates.io (with the same validation rules) that we can use for this?

**Comment by xgreenx** [comment]
We use [`katyo/publish-crates@v2`](https://github.com/katyo/publish-crates) action to publish all our crates, which supports `dry-run`. It performs most of the checks that should be done before publishing. It is not the same as publishing via `cargo publish`, but it should cover most cases.

We added a separate job [publish-crates-check](https://github.com/FuelLabs/fuel-core/pull/958/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f) that will perform those checks before actual publishing.

We also can troubleshoot the problem locally. How to do that is described in [this section](https://github.com/FuelLabs/fuel-core#publishing).

 I guess we can close the issue for now, but if it would be actual for us again, we can reopen it.
