### ISSUE TITLE
Create test to ensure executor gas price verification matches vm

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#424]
We currently have two places where we verify gas costs:

1. VM init
2. Executor

Until we consolidate this logic into something like a `CheckedTransaction` in fuel-tx, we need a test in fuel-core to ensure these validation functions don't drift.

ref: https://github.com/FuelLabs/fuel-core/pull/422#pullrequestreview-1010923845

**Comment by freesig** [comment]
This is done
