### ISSUE TITLE
Refactor cli to support subcommands

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-core#457]
Present client cli runs `fuel-core` by default but with the introduction of `snapshot` subcommand this becomes a little bit strange, as some flags get leaked inside `snapshot` that is not going to be used. And we can expect a new subcommand to appear in app.

Make subcommand `run` and move all flags under it.

clap example: https://github.com/clap-rs/clap/blob/v3.2.8/examples/cargo-example-derive.md
Commented here: https://github.com/FuelLabs/fuel-core/pull/435/files#r912957232

example of how it could look:
* `fuel run --config __`
* `fuel snapshot --db-path="db" --chain="{}"`
* `fuel vm (as example)`

**Comment by ControlCplusControlV** [comment]
Sway is a good example of how to model the new cli, with a high level enum that breaks into multiple subcommands [https://github.com/FuelLabs/sway/blob/master/forc/src/cli/mod.rs#L34](https://github.com/FuelLabs/sway/blob/master/forc/src/cli/mod.rs#L34)

**Comment by rakita** [comment]
> Sway is a good example of how to model the new cli, with a high level enum that breaks into multiple subcommands https://github.com/FuelLabs/sway/blob/master/forc/src/cli/mod.rs#L34

This looks nice and clean! from `cli` that specifies inputs to `ops` that specify an action.
