### ISSUE TITLE
Implement Peer Manager

### ISSUE THREAD

**Issue by leviathanbeak** [FuelLabs/fuel-core#460]
Peer Manager manages:
- peer connections
- peer pruning (of bad peers)
- peer reputation

Implement peer manager behavior
- [x] Maintain connection to reserved nodes (follow up from #779 )
- [ ] Reporting of invalid request response data
- [ ] Maintain a peer score / reputation

**Comment by Voxelot** [comment]
related: https://github.com/FuelLabs/fuel-core/pull/876

**Comment by Voxelot** [comment]
closing parent issue, we should create smaller tasks for the remaining work on peer reputation
