### ISSUE TITLE
Move db from `fuel-core` to `fuel-database`

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-core#464]
Mostly refactoring and cleanup. move all database related items to separate crate `fuel-database`.

**Comment by Voxelot** [comment]
deprioritizing this as we want to avoid:

service module crates taking a direct dependency on database / rocksdb, as that will drastically impact our unit testing performance
a large amount of churn while there are other critical tasks in flight
loose design / boundaries, the db-related logic in fuel-core could likely be split into several different crates more design and justification is necessary here.
