### ISSUE TITLE
Develop `fuel-metrics` crate

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-core#483]
Develop a `fuel-metrics` crate to handle tracking and metrics for each associated fuel service. This involves breaking out the existing fuel-core database metrics into this new crate. This also means

**Fuel-p2p**
- [ ] - Track maybe amount of p2p messages
- [ ] - Unique peers connected to
- [ ] - Track Transactions from peers

**Fuel-txpool**
- [x] - Average and Median Gas Price of a Tx  
- [ ] - Number of Pending Transactions
- [ ] - Average Lifespan of a transaction
- [x] - Average Gas of a Transaction
- [x] - Median Transaction size

**Comment by Voxelot** [comment]
Some additional metrics that would be useful

Block Stats (executor):
- [ ] histogram: block execution duration
- [ ] histogram: gas per block
- [ ] histogram: fee/coinbase per block
- [ ] histogram: txs per block
- [ ] histogram: I/O (db) time per block

**Comment by ControlCplusControlV** [comment]
Related #680

**Comment by Voxelot** [comment]
@ControlCplusControlV since this is marked as done, we should split the remaining metrics that aren't being collected yet into follow-up tasks.

**Comment by ControlCplusControlV** [comment]
#807 #808
