### ISSUE TITLE
Running --help or --version prepends `Error:` in the printed output

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuel-core#494]
Related: #468 

The usage of `try_parse` ([link to clap src](https://docs.rs/clap/3.1.18/src/clap/derive.rs.html#98)) seems to result in the printed message to be prefixed with `Error:` where unintended, especially when you run `fuel-core --version` or `fuel-core --help`:

![Screenshot 2022-07-18 at 4 28 01 PM](https://user-images.githubusercontent.com/25565268/179630102-c7a738b7-3f11-48d6-9669-6556f9a92ffc.png)

This is causing minor issues with `fuelup check`, since that command relies on parsing the output of `fuel-core --version`, and the output ended up being piped through stderr instead of stdout (which is what the command expects)

A possible solution, if there's no critical need to support the legacy cli (eg. possibly breaking CI scripts?), is to revert usage of `try_parse` back to `parse`, since running `fuel-core` on its own without the `run` arg would still show the usage message anyway, and we could add a usage comment on `run` to point users to type `fuel-core run` instead.

**Comment by rakita** [comment]
Fixesd
