### ISSUE TITLE
feat: have a flag for local development that enables/disables mutliple endpoints

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuel-core#497]
* Currently, running `fuel-core` binary forces you to enable a bunch of features if you want to use it locally. On the other hand, tons of endpoints are not needed when running a mainnet node. It would be nice to have a general flag for this with sensible defaults.

**Comment by Voxelot** [comment]
Ideally, we just retire some of these runtime flags like `utxo-validation` and `predicates-enabled`. The main blocker for this may be `forc run` and potentially Sway E2E tests which haven't been updated to use real coin inputs yet.

**Comment by MitchTurner** [comment]
We already have some things hidden behind debug. Also, it's not `fuel-core`'s responsibility to sculpt the api for the end user, that is up to the teams maintaining `forc`.
