### ISSUE TITLE
Fix typo in relayer

### ISSUE THREAD

**Issue by pixelcircuits** [FuelLabs/fuel-core#498]
There is a typo in the [RelayerArgs](https://github.com/FuelLabs/fuel-core/blob/589fd2f7ea7ec447e6c3af82c90831d7b3bfb4d9/fuel-core/src/cli/run/relayer.rs#L17) where `eth_v2_contracts_deployet` should actually be `eth_v2_contracts_deployment`

**Comment by Dinesh100K** [comment]
Hey can you assigned this to me? Thanks
