### ISSUE TITLE
Configurable Block Production Trigger

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#50]
Currently, blocks are produced instantly when transactions are submitted. In order to support multi-tx blocks, we need a configuration mechanism to enable/disable different block production triggers on startup.

e.g. `fuel-core run --block-production-mode interval` or `fuel-core run --block-production-mode instant`

This task should cover the implementation of the following block production options:

**`interval` Timer-based**: For simulating consensus block delays, the timer trigger will fire a block production event on a configurable interval
 **`instant` Instant trigger**: For integration testing contracts etc, make the tx pool trigger a block production event every time a tx is inserted.
**`none` No block production**: For passive nodes that simply listen for blocks

`pos` mode will be deferred to a later task.

**Comment by Dentosal** [comment]
For proof-of-authority network, should there exist a hybrid mode of interval and instant, similar to e.g. Nagle's algorithm? 

We have three timers, with following expiration times:
* A: Maximum block time
* B: Minimum allowed block time
* C: Maximum transaction idle time (shorter than A)

When a block is produced, restart timers A and B and clear timer C.
When a new transaction arrives, if timer C is not running, start it.
When either of timers A or C expires, produce a new block.
When a block is full and B has expired, produce a new block.

This way. we can produce new blocks faster than some fixed interval, but still include multiple transactions per block. The last timer, C, makes sure we will not produce blocks too quickly, so other nodes can still keep up.

**Comment by Voxelot** [comment]
This sounds great, and would also be useful in a rollup configuration without PoS. It helps avoid long strings of empty blocks when there's low activity.
