### ISSUE TITLE
support `nightly` releases and images

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuel-core#503]
`fuelup` aims to support 2 toolchains at the moment: `latest` and `nightly`:

__latest__: latest releases of `forc` and `fuel-core` that have passed integration tests with each other
__nightly__: latest successful builds of `forc` and `fuel-core` on `master` that have also passed integration tests with each other.

Currently, we support the `latest` toolchain with `fuelup`'s CI. We test the `latest` toolchain by polling for new releases, checking out the Sway repository using a newly released tag and run tests against a newly released `fuel-core` Docker image. You can check out the workflow [here](https://github.com/FuelLabs/fuelup/blob/master/.github/workflows/test-toolchain-compatibility.yml). We need to test this separately upon release because `fuel-core` versions are not always updated in the sway repo's CI.

`fuelup` requires nightly `fuel-core` releases (both as a binary for distribution and as a Docker image so we can pull it into the CI for tests).

The accompanying issue in the sway repo is [here](https://github.com/FuelLabs/sway/issues/1616)

cc @mitchmindtree

**Comment by Voxelot** [comment]
What kind of versioning scheme should we use for nightly releases?

**Comment by bingcicle** [comment]
I was thinking if we can still go with something like this: https://github.com/FuelLabs/sway/issues/79

**Comment by bingcicle** [comment]
Thinking back on this again, perhaps something like `nightly-YYYYMMDD-hash` works better so that fuelup can easily poll for new releases and run tests on them against nightly forc.

I'd be happy to pick this issue up myself (and the corresponding nightly issue in the Sway repo) since it should mostly be work on the workflow YAMLs, once we agree on the naming/versioning.

**Comment by bingcicle** [comment]
Closing this issue because both the workflow and the nightly binaries are now live in https://github.com/FuelLabs/sway-nightly-binaries
