### ISSUE TITLE
Create a fuel-core preview environment on every PR

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#504]
yes you can work on the PR for https://github.com/FuelLabs/fuel-core/pull/506/files -> you will need to create the logic

- build the docker image

- pass the image sha to tag in .github/workflows/deploy-test-env.yml (line 28) and then setup the trigger .github/workflows/deploy-test-env.yml based on PR

- the .github/workflows/delete-test-env.yml will be triggered when the PR is closed and/or merged

**Comment by rfuelsh** [comment]
already handled by https://github.com/FuelLabs/fuel-core/pull/506

**Comment by xgreenx** [comment]
> already handled by https://github.com/FuelLabs/fuel-core/pull/506

@Voxelot @rfuelsh  So, do we need this issue anymore?=)

**Comment by xgreenx** [comment]
Done
