### ISSUE TITLE
Refactor `FuelBlockHeader::number` to name `da_height` and type `DaBlockHeight`

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#516]

**Comment by ControlCplusControlV** [comment]
I was looking at this and `BlockHeight` is a `u32`, so all of its assosiated code is with that type, but since `da_height` is a u64 I am running into some incompatibilities. Should `da_height` be downgraded to `u32` or everything else moved to `u64`?

**Comment by bvrooman** [comment]
I think it's likely sufficient to use a `u32` for this purpose. The maximum value for a `u32` is in the realm of 4.3 billion, which should be more than enough.
