### ISSUE TITLE
fuel-core: running binary with `-V` errors

### ISSUE THREAD

**Issue by Wondertan** [FuelLabs/fuel-core#519]
```
❯ fuel-core -V // what is run
Error: fuel-core 0.9.6 // the output
```
The version is actually shown but as an error.

> I tried to find the reason myself, but this requires a deeper understanding of `clap`'s API, which I don't have

**Comment by ControlCplusControlV** [comment]
@Wondertan can you retry on fuel-core v0.10 ? I recently just re-ran this and got

```
➜  ~/test/ fuel-core -V
fuel-core 0.10.0
```
I installed via the cargo binary and ran from there (`cargo install fuel-core`)

**Comment by Wondertan** [comment]
Work fine now.
