### ISSUE TITLE
Layer 1 Relayer

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#52]
Fuel Core needs to communicate with Layer 1 in order to publish blocks and bridge assets.

- [ ] Generic interface (not eth specific)
  - [ ] validator staking events
  - [ ] asset deposits / withdrawals
  - [ ] block publishing 
- [ ] Mock layer 1 implementation (can be a simple rpc server with embedded db e.g. rocks or sqlite)
  - [ ] docker image
  - [ ] deployed via docker-compose & k8s
- [ ] L1 Relayer Adapters
  - [ ] in-memory (for unit testing)
  - [ ] Mock L1
  - [ ] Ethereum
- [ ] Service Configuration (e.g. cli args) allows choosing L1 adapter at runtime

**Comment by rakita** [comment]
Most of mechanisms are going to be explained in README that is going to follow the `fuel-relayer` crate.

For `Mock layer1 impl`, eth test networks are thing that is used and it is best to leverage.

Expanding on needed work:
* Initial sync from eth to fuel.
* Allow continuation of sync.
* Handling of pending eth events (Validator Deposit/WIthdrawal, token deposit) before they are finalized
* Handling of finalized validator set and current validator set. Have two different time sliders, one for eth finalization and second for fuel block validation.
* Expand DB to contain validator set diff and aggregated version of current best validator set.
* Expand DB to contain finalized token deposits.
* Make interface with rest of client module. Handle new FuelBlock from client, and request for getting ValidatorSet.
* Testing

Additional thing that is going to be left for future work:
* Create transaction for ethereum contract, handle signing and sending it over to ethereum. Handle GasPrice estimation, maybe contact some other service for that, (basefee is helping with better estimation)

**Comment by Voxelot** [comment]
What's included in the `Initial sync from eth to fuel.`?

**Comment by rakita** [comment]
> What's included in the `Initial sync from eth to fuel.`?

Waiting until Eth client is ready, fething all past events from eth contract and adding them in fuel client, it is needed when doing fuel initial sync. And switching from eth log fetch to filtering log via websocket and ensure that we dont miss any logs.

**Comment by rakita** [comment]
I am currently mocking ethers-rs provider/middleware so that i can make unit tests with simulated events.

**Comment by Voxelot** [comment]
That sounds good start. Mainly where I was coming from was that there should be a core handler for all the events that's chain agnostic / abstract, leaving things like chain finality or specifics around ethers-rs to an adapter. That way we can just rewrite the adapter for eth2 vs celestia or some other L1 bridge we may want to support in the future without a drastic re-write.

**Comment by adlerjohn** [comment]
Agree with @Voxelot here, because e.g. the notion of re-orgs is an Ethereum-specific thing. Tendermint-based chains like Celestia won't have re-orgs.

**Comment by rakita** [comment]
I Agree, lets do it for ethereum and when celestia comes we can see what are differences and what can be reused and make abstraction then.  And to be fair, current impl is quite abstracted with `fuel-core-interfaces`.

**Comment by Voxelot** [comment]
Make sense, unless there's some common abstract implemtation needed (which there might not be other than how events get triggered), the interfaces should be sufficient for this need.

**Comment by Voxelot** [comment]
closing since relayer is already far along, and we should use smaller tasks for additional work.
