### ISSUE TITLE
Investigate Weird bug with `tx::utxo_validation::concurrent_tx_submission_produces_expected_blocks`

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-core#523]
Weird bug observed with [this CI run failing](https://github.com/FuelLabs/fuel-core/runs/7615560895?check_suite_focus=true) while [upon a re-run it succeeded ](https://github.com/FuelLabs/fuel-core/runs/7615560895?check_suite_focus=true)

**Comment by Voxelot** [comment]
Timebox 1-2 days of investigating

**Comment by Voxelot** [comment]
I think this is due to the new event based the transaction pool is using, as we only await queuing the removal of txs, rather than waiting for them to actually get removed.
