### ISSUE TITLE
Correctly implement merkle storage

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#527]
- [x] #629
- [x] #626
- [x] #627
- [x] #628
- [x] #633
- [x] #634
- [x] https://github.com/FuelLabs/fuel-merkle/issues/113
- [x] https://github.com/FuelLabs/fuel-merkle/issues/114 
- [x] https://github.com/FuelLabs/fuel-vm/issues/311

**Comment by Voxelot** [comment]
Based on discussions with @adlerjohn, the current list of merkle trees that span data across blocks would be:

- Contract Balances (SMT)
- Contract State (SMT)
- Block IDs MMR (binary tree)
  - Unlike other chains that just include a hash of the previous block into the current block header, Fuel will use a merkle mountain range of block ids and store the current root on each header. This allows L1 proofs about data in previous block headers without needing to maintain the state of all headers in L1.

The areas we can use ephemeral trees would be the following block header fields:

- Transactions Root (BMT)
- Output Messages Root (BMT)

**Comment by bvrooman** [comment]
On going research document: https://hackmd.io/@bvrooman/merklized_data_on_disk

**Comment by bvrooman** [comment]
> The areas we can use ephemeral trees would be the following block header fields:
> 
> * Transactions Root (BMT)
> * Output Messages Root (BMT)

According to the [WIP spec](https://github.com/FuelLabs/fuel-specs/issues/284), there is a field for Withdrawals Root. I do not see Output Messages Root mentioned. Are these the same thing, just different terminology? Or is there a discrepancy?

**Comment by xgreenx** [comment]
@bvrooman Seems we can close https://github.com/FuelLabs/fuel-core/issues/527, because it is tracked here=)
