### ISSUE TITLE
feat: add an option for silent node running 

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuel-core#534]
Currently, the only way to have a node being silent while running is to set the output to `null`. However, in practice this cannot be done, for instance in the SDK. It would be nice to have a `--silent` flag which deletes all output, and the corresponding configuration option.

**Comment by Voxelot** [comment]
Is this when the node is spawned in subshell or when used as a library? Generally managing how logs are captured should be easily configurable and handled by the user rather than the app itself.

**Comment by iqdecay** [comment]
This issue was created because when the node is not used as a library (ie with the binary), running `cargo test` in the SDK spams console with:
```rust
2022-08-05T14:41:41.067892Z  INFO new_node: fuel_core::service::graph_api: 72: Binding GraphQL provider to 127.0.0.1:20805
2022-08-05T14:41:41.072885Z  INFO fuel_core::cli::run: 111: Fuel Core version v0.9.8
2022-08-05T14:41:41.073567Z  INFO new_node: fuel_core::service::graph_api: 72: Binding GraphQL provider to 127.0.0.1:17724
```
I didn't see an option for the "silent" running of the node. This is how the node is run within the SDK:

https://github.com/FuelLabs/fuels-rs/blob/4ef97778ef693c7c494b08e681bf6c9ef86e21e3/packages/fuels-test-helpers/src/node.rs#L253

**Comment by Voxelot** [comment]
Closing as this is a bug with how streams are being managed via the SDK harness https://github.com/FuelLabs/fuels-rs/pull/479

The fix should be done in the SDK harness.
