### ISSUE TITLE
Review Imports

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-core#537]
Review Imports, several places where nested imports are needed. Also make sure all importing is done through `fuel_core_interfaces` rather than directly

**Comment by Ch1n3du** [comment]
Is this issue still open? I'd like to give it a try.

**Comment by ControlCplusControlV** [comment]
Yes, go for it!

**Comment by Ch1n3du** [comment]
What style do you prefer 

## One:
![Screenshot from 2022-08-19 10-20-40](https://user-images.githubusercontent.com/38131869/185587995-88791fce-2f9a-4d85-a596-aa5c57d2b1cb.png)

## Two:
![Screenshot from 2022-08-19 10-20-30](https://user-images.githubusercontent.com/38131869/185587875-cf8ed034-3d23-43bc-a941-872fe4b05d78.png)

**Comment by Ch1n3du** [comment]
Currently I'm using the first style but the second seems a bit more readable

**Comment by Voxelot** [comment]
I think rustfmt would only allow the first option 🤔

**Comment by Ch1n3du** [comment]
Made a pr I had some issues I wasn't able to solve.

**Comment by Voxelot** [comment]
closing as our new nightly rustfmt config resolves this issue
