### ISSUE TITLE
Unify names of our mpsc channels

### ISSUE THREAD

**Issue by leviathanbeak** [FuelLabs/fuel-core#556]
While #492 has not yet been merged, in it we use `rx` and `tx` prefixes when naming our `Sender` and `Receiver` channels.
An example would be `rx_request_event`. 

In other modules, channel names do not follow that convention, even worse (imo) they are too vague as:
`sender`, `broadcast`, `receive` etc

I would like us to have more meaningful and unified channel names.
I propose `rx`/`tx` prefixes + descriptive name, but I am open to other ideas as well.

**Comment by Dentosal** [comment]
This is otherwise nice, but unfortunately `tx` is used for transaction in many contexts, which might be confusing.

**Comment by Voxelot** [comment]
closing as the channels have been largely removed during the architecture migration
