### ISSUE TITLE
Add GraphQL API for getting merkle proofs of output messages

### ISSUE THREAD

**Issue by pixelcircuits** [FuelLabs/fuel-core#567]
In order for integration tests to test messages sent from Fuel to the base chain (Ethereum) there needs to be an endpoint in the GraphQL API that can return a valid merkle proof to relay an output message after it has been committed. A lot of the objects and patterns with this API will be similar to what gets defined for [this issue](https://github.com/FuelLabs/fuel-core/issues/566), although this new merkle proof API will likely need to come first.

There might be some overlap with [this issue](https://github.com/FuelLabs/fuel-core/issues/528) as well.

Here is a rough outline of what this could look like:
```
/*==Objects==*/
MessageProof {
  messageId: MessageId
  root: U256
  key: U256
  numLeaves: U256
  data: [U256]
}

/*==Queries==*/
Query messagesToProve
  arguments
    messageIds: [MessageId]
  fields
    nodes: [MessageProof]

```

**Comment by Voxelot** [comment]
Based on a few rounds of discussion, here's a high level view of what is needed from the API:

inputs:
 - transactionID which contains the withdrawal message being proved.
 - messageID of the message to generate a proof for.

outputs:
 - Signed Fuel Block Headers which contain the transactionID in the transactionRoot
 - Merkle proof of input messageID to the block header messages merkle root
 - A Message containing all fields the contract would need to verify the messageID

Requirements for the proof:

- The block header's message output root should be built using a binary merkle tree (BMT) of all message IDs output from a block.
- The message root BMT leaves should rely on the total ordering across all message receipts within a block. This means we'll need to fetch all receipts for every tx based on the tx block ordering, filter on message receipts, and map those into messageIDs for the merkle tree leaves.
- The returned message object contains all receipt fields needed to regenerate a [messageID](https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/identifiers.md#message-id). These are all available on the message receipt associated with the transactionID and messageID provided as inputs to the API.

**Comment by Voxelot** [comment]
blocked by: #674 #673
