### ISSUE TITLE
Does Panic Receipt `reason` encoding match the spec?

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuel-core#585]
In the spec, the Panic Receipt reason is [`u8`](https://github.com/FuelLabs/fuel-specs/blob/8bb43ae61aab69e72275c004792aef34efed1d9b/specs/protocol/abi.md#panic-receipt).  But the currently its [`u64` ](https://github.com/FuelLabs/fuel-core/blob/0a36d473b3575ff08684a2d8e730aaafe44a46c6/fuel-client/assets/schema.sdl#L460) in the schema.  

Also should panic receipt reason `u8` value map to values https://docs.rs/fuel-asm/latest/fuel_asm/enum.PanicReason.html

**Comment by QuinnLee** [comment]
@Voxelot I'm not sure if this issue is the right place. feel free to re-label or close this

**Comment by Voxelot** [comment]
The spec generally only prescribes how types should be aligned and formatted within the VM, and things like GraphQL schemas would be what's known as an "implementation detail". I see no reason why we can't change this to a u8 in our Rust types, however, unless we create a special `U8` GraphQL scalar, the GraphQL API would just treat a u8 as a regular javascript number. 

Would you prefer a custom U8 scalar, or is the concern mostly about having the reason encoded into a string?
