### ISSUE TITLE
While printing initial accounts, output `Bech32Address` so that it can be used out-of-box with `forc-{deploy, run}`

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuel-core#593]
In a recent discussion with @adlerjohn over slack, we discussed the possibility of outputting `Bech32Address` as the address for the initial accounts so that they can be directly used in `forc-{deploy, run}`.

**Comment by kayagokalp** [comment]
Looks like fuel-core stopped emitting initial account addresses in `bech32` format as of #635. Since forc-wallet supports signing with provided `bech32` format, it is not possible to sign transactions for the local node while using the initial accounts. Not sure if this is intentional or a regression but it would be great if we can get this back 👀

**Comment by xgreenx** [comment]
Yeah, it is regression, while moving the file we lost your change https://github.com/FuelLabs/fuel-core/pull/635/files#diff-117c8f6c8f71748ba4f5727d134b81015097f489abe99df6051067e1e47a8f20
