### ISSUE TITLE
Avoid Using random feature in `fuel-vm` features

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-core#607]
hmm this will enable lots of random functions we may not want to allow access to in production code 🤔 

As a tech-debt follow-up, we'll need to figure out a different way to solve the need to use random in fuel-crypto, without enabling it in everything else.

_Originally posted by @Voxelot in https://github.com/FuelLabs/fuel-core/pull/605#discussion_r967571069_

**Comment by xgreenx** [comment]
Is not actual anymore
