### ISSUE TITLE
Include messages in balance API

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#614]
When the user requests a balance, it can be represented by `Coin`s and `Message`s. We need to update `fuel-core/fuel-core/src/schema/balance.rs` to take into account the `Message`s.

It easy can be done with the usage of the `AssetQuery` from https://github.com/FuelLabs/fuel-core/pull/591.

**Comment by Voxelot** [comment]
Also note: messages only directly affect the balance of the default base asset. Even if it includes the data for some other kind of asset deposit, that shouldn't be factored into the balances until the message is redeemed.
