### ISSUE TITLE
Merkle root for Contract state

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#627]
- [ ] Contract state is accumulated in a persistent sparse Merkle tree (SMT)
- [ ] The `contractStateRoot` is calculated from the SMT using all contract state

TODO: How is the contract state Merkle root used?

**Comment by ControlCplusControlV** [comment]
@bvrooman main use of a contract state root us will be with fraud proofs, if you have the state root for a contract you can prove the values in specific storage slots before executing an opcode on L1. AFAIK it also helps with some light client things
