### ISSUE TITLE
Merkle root for a Block's Transactions

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#633]
Note: this may already be done but is included in the parent story for the sake of completeness. Assess the completeness of transactionRoots in the context of the wider Merkle storage story. 

- [x] Transaction IDs within a Block are accumulated in an in-memory binary Merkle tree (BMT)
- [x] The `transactionsRoot` is calculated from the BMT using all transactions from the current Block
- [x] The calculated `transactionsRoot` is written to the current Block's headers
- [x] The calculated `transactionsRoot` is compared to the Block's asserted `transactionsRoot` during Block validation. Validation fails with an error if the roots do not match.

**Comment by mitch-fuel** [comment]
By comparing the pre-execution block id to the finalized block id, both of which use the `transactionsRoot`, validation of the `transactionsRoot` root is performed for every block validation.
