### ISSUE TITLE
Use fuel.nix flake dev shell in CI

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#641]
We should be able to substantially reduce our CI times by using the new fuel.nix flake's fuel-core-dev shell. This is due to using a precompiled version of RocksDB which takes up the majority of our compilation time.

Related RocksDB optimization: https://github.com/FuelLabs/fuel.nix/pull/21

This will involve the following steps:

- install nix with flake support using the official nix cachix action: https://github.com/cachix/install-nix-action#usage-with-flakes
- Add the following config to the `with: extra_nix_config` section:
```
substituters = https://cache.nixos.org/ https://mitchmindtree-fuellabs.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= mitchmindtree-fuellabs.cachix.org-1:UDUQvwjM3wRCZe1chrgqAehb3M0M5x9qjpEwJwPn7Ik=
```
- start the fuel-core dev shell before running any cargo commands like check or test:
```
nix develop github:fuellabs/fuel.nix#fuel-core-dev
```

There may be a chicken-and-egg problem to solve when upgrading the Rust version of fuel-core, as it is currently set automatically in the flake based on a fuel-core nightly release. We may need to use flake tags instead of relying on nix to automatically select the right version of Rust.

**Comment by ef3n9r98** [comment]
Hi @Voxelot, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by Voxelot** [comment]
nix is not very performant in CI
