### ISSUE TITLE
Add chainId and chainspec validation to peering process

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#646]
The peering process should invalidate connections to peers with a different chain id or chain config. 

While we currently segment peers based on a network name, we should take further measures to prevent fuel nodes from different networks (e.g. testnet vs mainnet) from peering with each other.

Each chainconfig contains its own unique genesis values such as initial balances or initial state. We also plan to have a chain identifier to help differentiate between testnets with similar genesis values. When connecting to a new peer, we should request a checksum (sha256) of these unique values (chain ID + chain_config) and compare with a local checksum before adding to the peerset.

**Comment by leviathanbeak** [comment]
Investigated the approach for this,
this can be achieved by applying and implementing inbound/outbound upgrades to libp2p's connections.

Working on it
