### ISSUE TITLE
Expose P2P network information from the P2P orchestrator 

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#649]
Getting currently connected peers:
- [ ] `get_peers()` method on network service returns the list of currently connected peers
- [ ] `Peers` schema in `fuel-core`
- [ ] GraphQL endpoint for retrieving `Peers` where the list of peers is populated by calling `get_peers()`  on network service
- [ ] Schema wrapper in `fuel-client`
- [ ] `get_peers()` method on client returns the list of peers populated by querying GraphQL for peers

**Comment by bvrooman** [comment]
Blocked on ongoing P2P upgrades

**Comment by Voxelot** [comment]
this should be unblocked now

**Comment by xgreenx** [comment]
@leviathanbeak @bvrooman What is the status of this issue right now?
