### ISSUE TITLE
Put inbound and outbound p2p requests behind an atomic lock

### ISSUE THREAD

**Issue by leviathanbeak** [FuelLabs/fuel-core#669]
As pointed out by @xgreenx [here](https://github.com/FuelLabs/fuel-core/pull/661#discussion_r985651948) our inbound and outbound requests that are stored in a HashMap should be behind Atomic lock to provide safe concurrent access

**Comment by freesig** [comment]
I'm not sure I understand this as both calls take `&mut self` so it's already safe to concurrently access as you can't have more then one `&mut` or it won't compile. Or am I missing something?

**Comment by xgreenx** [comment]
Yes, you are right=) I thought we had two separate loops to handle input and output events, but no. This loop only takes the next not `None` event. So we have only one main loop in the `NetworkOrchestrator::run` and we can close this issue=)

<img width="812" alt="image" src="https://user-images.githubusercontent.com/18346821/194515564-a300ba0a-cfe2-432f-af02-5c31e0f5a259.png">

Another question to @leviathanbeak , Why do we need this loop? Waiting inside this loop blocks our main loop.

**Comment by leviathanbeak** [comment]
@freesig you are correct, I kind of created this based on feedback in a rush, but it did feel wrong, my idea was to investigate it but you guys already did a sanity check :) so thanks

**Comment by leviathanbeak** [comment]
@xgreenx good catch, that `loop` was there as an event loop before the Network Orchestrator was created, now it's a bit redundant since we have the pattern `loop` & `select!` within the orchestrator. I will remove it in today's PR.
