### ISSUE TITLE
Acceptance testing for relayer

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#676]
run e2e tests against a deployed fuel node connected to a deployed test ethereum node in k8s

Env should already have:
- deployed smart contracts (see if we can include into eth chainspec)
- issued test txs for messages on eth

Test:
- verify messages are spendable

TODO:

- [ ] automate deployment of the L1 image to fuel-core test environments in k8s [deploy-test-env](https://github.com/FuelLabs/fuel-deployment/blob/master/.github/workflows/deploy-test-env.yml) (blocked by https://github.com/FuelLabs/fuel-dev-env/issues/1)
- [ ] automate deployment of fuel contracts to fuel-core in test environments once fuel-core is started [deploy-test-env](https://github.com/FuelLabs/fuel-deployment/blob/master/.github/workflows/deploy-test-env.yml)
- [ ] run [bridge tests](https://github.com/FuelLabs/bridge-integration-tests) from CI (maybe in a new acceptance test repo?)

**Comment by xgreenx** [comment]
Hmm, seems we can add https://github.com/FuelLabs/fuel-core/issues/671 as one of the points here? 
Also, do we want this to be done for beta 4? Or for mainnet?

**Comment by xgreenx** [comment]
@Voxelot Do we need this issue? It seems like `fuel-bridge` covers e2e of how relayer works

**Comment by xgreenx** [comment]
Closing for now since we have a separate repository with e2e tests.
