### ISSUE TITLE
Integrate block trigger with block producer, and remove graphql driven production

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#677]
Eliminate the need for `Executor::submit_txs` using the real block production trigger https://github.com/FuelLabs/fuel-core/pull/599 instead. Transactions must be removed from the txpool when blocks are produced as well.

Debugging and dry run functionaly should be implemented for this system as well, but that can be deferred to a later issue.

**Comment by Dentosal** [comment]
@Voxelot  Should the dry-run functionality still run a single one-transaction block and ignore the block production trigger system completely?  Or should it create a new block with currently available transactions and dry-run them all?
