### ISSUE TITLE
Idempotent message insertion

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-core#681]
Another separate concern is that the way we are inserting messsage in our DB could overwrite the spent status if the message was already downloaded on a previous attempt, allowing for double spend. For example, if the write log fails after partially saving a page and then retries again sometime later, a user could have spent one of the messages that made it into the DB (changing its state). When the relayer retries and overwrites the message, the spent status field would be reset, making the message elidgable for spending again. 

We should check if the message ID exists before saving it to avoid issues with this method not being idempotent. While the previous fix reduces the window of time that this could happen, it's still a risk even if we only have a lag-1 page retry. 

In the future, it might be worth tracking the spent status of messages in a separate column to be able to safely prune the data of spent messages from state without risking double-spends in case the relayer da_height is reset for some reason.

_Originally posted by @Voxelot in https://github.com/FuelLabs/fuel-core/pull/631#discussion_r988247445_

**Comment by xgreenx** [comment]
Related https://github.com/FuelLabs/fuel-core/issues/781
