### ISSUE TITLE
Make relayer flake.nix docs beginner friendly

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-core#686]
From a fresh install I tried the commands and regularly ran into use '--extra-experimental-features nix-command` and use '--extra-experimental-features flakes` being required. Then a github permissions issue on `fuel-v2-contracts` (presumably because I haven't setup git with nix right)

_Originally posted by @ControlCplusControlV in https://github.com/FuelLabs/fuel-core/pull/665#pullrequestreview-1135253140_

The `fuel-v2-contracts` is due to it being a private repo and needing git ssh setup

**Comment by xgreenx** [comment]
https://github.com/FuelLabs/fuel-block-committer/blob/bb352c6164745bf0d15ea0e971f78f8db13f1c2e/src/adapters/ethereum_adapter/websocket/adapter.rs#L24
