### ISSUE TITLE
The proper handling of invalid transactions during block execution

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#738]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/18346821/198714051-0c0eb5cb-adbb-4747-9b11-a8d56a5c41ab.png">

Any invalid transaction in the `TxPool` ruins block production. We need to handle it for stable production.
It seems the best way is to exclude failed transactions from the block and continue block generation(Without interruption). As the result of block execution, we can return generated block, and skipped transactions. `TxPool` can validate skipped transactions and clean them up or include block production again.

**Comment by Voxelot** [comment]
We also should figure out why invalid txs were able to make it to the block producer in the place and update the txpool validation accordingly.

**Comment by xgreenx** [comment]
> We also should figure out why invalid txs were able to make it to the block producer in the place and update the txpool validation accordingly.

The cause was a misconfiguration https://github.com/FuelLabs/fuel-core/pull/743
