### ISSUE TITLE
investigate whether splitting debug info will speed up debug builds

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#750]
splitting debug info into a separate file may reduce linking times for debug builds. This is now possible as of rust 1.65

https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#splitting-linux-debuginfo

We should also verify the impact of this on debuggability, as common dev tools might not be adapted to support this feature yet.

**Comment by ControlCplusControlV** [comment]
`RUSTFLAGS="-C split-debuginfo=unpacked" cargo build` has a runtime of 2 minutes for me, and so does `cargo build` (after a cargo clean for both on fuel-core) so it looks like build speed is about the same regardless of the flag's status
