### ISSUE TITLE
TxPool test suite must cover success cases and failure cases

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-core#762]
Currently, the TxPool test suite covers:
- Simple success cases (simple insertion, simple dependency chains)
- Most error cases

The TxPool test suite does not cover:
- Complex dependency chains
- All error cases (there are more `Error` variants than tests)
- Stress testing (high volume, high concurrency, etc.)
- Benchmarking

**Comment by xgreenx** [comment]
Transaction Pool V2 improves the test coverage https://github.com/FuelLabs/fuel-core/pull/2193

**Comment by AurelienFT** [comment]
I think this can still be open as I improved a bit but mainly reordered and simplified and there is points like benchmarks that I don't have and should be done.
