### ISSUE TITLE
Make a `rust-toolchain.toml`

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-core#771]
As seen in in the [Cargo Book](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) `fuel-core` and all associated repos should have a `rust-toolchain.toml` specifying a toolchain which the repo is tested and built with

**Comment by Voxelot** [comment]
It seems like this is more heavily recommended when you need to pin nightly versions of rust.

**Comment by ControlCplusControlV** [comment]
Yeah, apparently this can hook with github actions, but is currently blocked by actions-rs being unmaintained, which is explained more [here ](https://github.com/FuelLabs/sway/pull/3370#event-7877510418). Closing for aforementioned reasons there though
