### ISSUE TITLE
Investigate alternatives to bincode serialization

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-core#776]
Maybe instead of `serde` and `bincode`, we could use something like [`rkyv`](https://docs.rs/rkyv/latest/rkyv/)? In any case, `bincode` format isn't stable across Rust versions and should not be used for persistent storage.

**Comment by ControlCplusControlV** [comment]
Will note serialization for database and p2p should probably be separate, since changing p2p serialization will cause Consensus issues, while database serialization will not necessarily do that
