### ISSUE TITLE
Test relayer can't double spend

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-core#781]
Check the relayer can't download same message twice and set from spent to unspent

**Comment by Voxelot** [comment]
Make relayer downloading of messages idempotent in case we need to resync (e.g. due to a changed contract id that needs to be reindexed)

**Comment by freesig** [comment]
- [ ] Use a db transaction for downloading logs and don't commit unless all logs are finished downloading.
	- [ ] Make sure that when committing it is for entire block (or range of blocks)
- [ ] Separate column for relayer to write messages and da heights.
- [ ] Only pull messages into main db column in order of da height.
- [ ] Move spawn blocking down to execute call
- [ ] Pull messages for current_da_height + 1 from relayer to db transaction during commit result.
- [ ] Only messages up to the current fuel blocks da height should exist in the main db messages column.
- [ ] Remove messages from relayer once block successfully executes but in the same db transaction.
