### ISSUE TITLE
Replace the GraphQL interface with client-as-a-library and a minimal RPC

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-core#782]
As discusses with the indexer team, we should be minimize the interface fuel-core exposes, and instead move the aggregate queries to the indexer.

**Comment by xgreenx** [comment]
It is a duplicate of the https://github.com/FuelLabs/fuel-core/issues/588. We need to decide which issue will be main=)

**Comment by Voxelot** [comment]
closing in favor of #588
