### ISSUE TITLE
use anyhow! or some other kind of generic error wrapper instead of std::io::error

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#801]
We use std::io::Error in many places as a generic catch-all for various errors. This isn't very ergonomic when compared to proper error libraries like `anyhow!`. Since we already use anyhow in many places we should convert the remaining uses of std::io::Error to use anyhow in our public interfaces (such as the fuel-client).

We could also investigate other alternatives to anyhow if we want better no-std support.

**Comment by Voxelot** [comment]
Anyhow actually does seem to have good no-std support. Switching the vm over may enable it to be fully no-std / wasm compatible.

**Comment by xgreenx** [comment]
During refactoring for `no_std` support in `fuel-vm` we replaced `std::io::Error` with anyhow or another errors.
