### ISSUE TITLE
Allow resourcesToSpend to select from pending txpool outputs 

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#803]
# Problem

Under heavy concurrent load, the faucet sporadically runs out of coins to spend when it's coins are tied up in txs that are still pending in the pool. This leads to errors such as "coin already spent" as the same coins are selected multiple times.

# Proposed Solution

To improve the experience for SDK users when submitting many transactions concurrently, the resoucesToSpend API could be updated with the following features:

2. if there are not enough "resources" to reach the spending target, allow the selection algorithm to use available coin outputs on pending txs in the txpool
3. exclude coins that exist on transaction inputs in the txpool.

This will in-effect lower the probability that coins are redundantly selected for spending, and allow users to queue up multiple txs at once based on pending outputs.

# Caveats

### Client side race conditions
Excluding txpool pending input coins from the selection may not be entirely robust if two requests for resourcesToSpend are sent concurrently and they select the same coins before either tx is submitted. While the server could allow each request to resourcesToSpend to mark and lock the returned utxos to avoid this contention, that could be a DOS vector for users if a malicious actor continuously locked coins they don't own on public api nodes. It also isn't resilient in the face of load-balanced requests. 

The best solution is for the sdk / api caller to create a local pool of utxo candidates and locally check for conflicting spend inputs on their own. resourcesToSpend could be called optimistically, and retried until a non-conflicting set of inputs is found. Any inputs already in the local SDK pool should be added to the exclusion parameters of the resourcesToSpend API, forcing the API to reach into the pending utxo set if there are not enough finalized utxos to select from. Alternately, sdk users should simply just wait for a tx to be successfully submitted to the txpool (they don't need to wait for finalization though) before starting any new transactions.
 
###  Tx Pool Max Depth
The txpool has a max-depth preventing tx dependency chains from getting too deep. resourcesToSpend shouldn't select from any pending utxos at the max-depth, and return an error such as "found sufficient resources but reached txpool depth limit".

### Selecting from Pending Change & Variable Outputs
Assuming most of the pending outputs will be change outputs, their amount will remain zeroed out until the tx is fully executed & unused gas is refunded. For create txs, the change amounts can be determined in advance. However, script transactions may use up all the available free balance leaving the change amount zeroed. There's no clean way predict how much change will be returned in a script tx as it could depend on the state of the chain at the time the script is fully evaluated in a block  - unless the script is empty / noop for simple transfers.

The simplest solution is to ignore change & variable outputs from transactions containing non-empty scripts during coin selection, and simply just return an error like "failed to find sufficient resources".

**Comment by freesig** [comment]
Wow this is a pretty complex problem

**Comment by freesig** [comment]
This feels a lot like a `compare_and_swap` problem. The issue here is that the total order is only decided after the txns are including in the block. So what we are trying to do is predict which utxos will be included and suggest that the user doesn't try to spend them. I don't think this can be much stronger then a suggestions as if we try an enforce a total order on the api call then you run into the problems you describe above.

**Comment by xgreenx** [comment]
The SDK basically has support for caching of the outputs already and it is kind of behaviour that we wanted. So I think from our side we don't need to support it since it complicates code a lot=)
