### ISSUE TITLE
Fuel-Executor Metrics

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-core#807]
Scope changes:

The following metrics will be added
- [x] histogram: gas per block
- [x] histogram: size per block
- [x] histogram: fee/coinbase per block
- [x] histogram: txs per block

The following metric will not be added as a part of this issue. We will discuss if we want some more sophisticated mechanism to measure other operations that touch DB
- histogram: I/O (db) time per block

The following metric will not be added
- gas prices
Rationale: https://github.com/FuelLabs/fuel-core/issues/807#issuecomment-2399568615

cc: @acerone85 @MitchTurner

**Comment by rafal-ch** [comment]
Question regarding "histogram: I/O (db) time per block" - what we actually try to measure here?

Are we interested in how much time was spent on the DB operations in `Importer::execute_and_commit`?

This would require measuring call-chain such as:
* `verify_block_fields()`
  * `block_header_merkle_root()`
  * `block_header()`
* `validate()`
  * `native_validate_inner()` -or- `wasm_validate_inner()`
  * potential call to `get_module()` in `validate_inner()`
* `_commit_result()`
* _possibly more..._

And then, next to
```
importer_metrics().execute_and_commit_duration.observe(time);
```
we can add
```
importer_metrics().execute_and_commit_db_duration.observe(time);
```

---
Alternatively, we might want to work on a generic method of opt-in for measured DB reads, like `trait MeasuredStorageInspect` or similar.

---
Any opinions? @xgreenx @acerone85

**Comment by rafal-ch** [comment]
Also, what would be the suggested values for [FEE_BUCKETS](https://github.com/FuelLabs/fuel-core/pull/2310/files#diff-aeaabf5017706a3cb5bde99ae87c72479ca92706edbdee386c8274b1826dfb9bR61) and [GAS_PRICE_BUCKETS](https://github.com/FuelLabs/fuel-core/pull/2310/files#diff-aeaabf5017706a3cb5bde99ae87c72479ca92706edbdee386c8274b1826dfb9bR71) buckets.

**Comment by MitchTurner** [comment]
> The gas price is not available from the block importer, but rather from the producer.
Should we add metrics for the block producer too @MitchTurner?

Perhaps we put the metrics on the `gas-price-service` since it holds the most context? It's available from the producer, the tx-pool, and graphql, but they all get it served from the gas price service.

**Comment by rafal-ch** [comment]
As for now, we're not gonna be doing the "gas price" metric. Rationale: Since we don't have DA gas price yet, we can derive the total gas price from gas used and fee.

**Comment by MitchTurner** [comment]
Everything looks completed :)
