### ISSUE TITLE
Fuel-P2P Metrics

### ISSUE THREAD

**Issue by ControlCplusControlV** [FuelLabs/fuel-core#808]
Also look at gossipsub metrics config and use real parameters

**Fuel-p2p**
- [ ] - Track maybe amount of p2p messages
- [ ] - Unique peers connected to
- [ ] - Track Transactions from peers

**Comment by AurelienFT** [comment]
@rafal-ch can we consider this as done or there is more things to add ?

**Comment by rafal-ch** [comment]
> @rafal-ch can we consider this as done or there is more things to add ?

I'm not sure, tbh. @rymnc added quite a lot of P2M metrics in [this commit](https://github.com/FuelLabs/fuel-core/pull/2310/commits/76b10848a64cf40d3ca537a23ebb7c2a548ff9b1), but they seem to be more "low-level" than the ones mentioned in the description. For example, I don't see a metric for "Track Transactions from peers".

We should double-check with @rymnc or discuss on the grooming.

**Comment by rymnc** [comment]
we can close this issue as p2p metrics have been added and transactions are tracked via txpool metrics
