### ISSUE TITLE
Socket hang up error while trying to send a request to the local fuel node

### ISSUE THREAD

**Issue by meliksahgurtemel** [FuelLabs/fuel-core#820]
I am not sure if it's related to fuel-core but when I am trying to test my contract by using ts-sdk, I get this error even the fuel node is running locally:

```
FetchError: request to http://127.0.0.1:4000/graphql/ failed, reason: socket hang up
   at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1491:11)
```

I'm using fuel-core v0.14.1

**Comment by xgreenx** [comment]
@meliksahgurtemel Did you manage to resolve your problem? If yes, maybe you could describe how? If not, and you still need help with it, could you provide details about your setup/steps?
