### ISSUE TITLE
Unify `chain_id` generation and usage across services

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#824]
https://github.com/FuelLabs/fuel-core/pull/785#discussion_r1043812652
https://github.com/FuelLabs/fuel-core/pull/785#discussion_r1043813806

> Also, these root functions should exist in the chain-config module so that they can be used without fuel-core. As fuel-p2p is in it's own crate and won't be able to use the genesis module directly.

Means also need to move all stuff regarding the genesis root calculation into `fuel-chain-config`, because it is where it belongs. Also, `Genesis` should be a part of the `ChainConfig` and `initial_state` field only as metadata without any impact on the root calculation.

**Comment by Voxelot** [comment]
> initial_state field only as metadata without any impact on the root calculation.

We had a subsequent discussion and decided that the initial state should be included in the global genesis commitment

cc @leviathanbeak
