### ISSUE TITLE
Sentry Node

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#85]
In order to secure our network in sidechain mode, we'll need to operate sentries that monitor the consensus behaviors of participants for any foul play (e.g. vote withholding or voting for invalid blocks). This will also need to page the security team when problems are discovered.

**Comment by Dentosal** [comment]
Related https://github.com/FuelLabs/fuel-core/issues/647 and https://github.com/FuelLabs/fuel-core/issues/645
