### ISSUE TITLE
PoA Hybrid trigger doesn't respect min_block_time if tx_idle_time is lower

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#866]
# Problem:
When using the Hybrid trigger in the PoA coordinator, if tx_idle_time < min_block_time blocks are produced at a rate faster than min_block_time allows. tx_idle_time is intended to create a ["debounce"](https://reactivex.io/documentation/operators/debounce.html) timeout effect, which waits a short amount of time for additional transactions to become included in the block after the initial tx instead of immediately constructing a block whenever a new tx comes in.

# Expected Behavior:

min_block_time should never be violated, as it is intended to rate-limit blocks so that synchronization can keep up. tx_idle_time shouldn't override `last_block_produced_time + min_block_time`, and only take affect if we are in-between min_block_time and max_block_time.

cc @Dentosal

**Comment by xgreenx** [comment]
Close in favor https://github.com/FuelLabs/fuel-core/issues/1182
