### ISSUE TITLE
Investigate Optimizations of Range State Clear

### ISSUE THREAD

**Issue by ghost** [FuelLabs/fuel-core#867]
A potential optimization of SCWQ and the underlying `merkle_contract_state_remove_range` would be to use an iterator to determine whether to a remove call needs to be made in the event that the state was already unset.

**Comment by xgreenx** [comment]
It is not clear if we need sequence opcodes at all, because after https://github.com/FuelLabs/fuel-specs/issues/517 we can remove it. The priority of this issue is not clear until we decide on dynamic storage.
