### ISSUE TITLE
Remove txs from txpool without dependencies

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#868]
When a block is produced or imported, the associated txs need to be removed from the pool. However, our current removal method assumes that the tx and all it's dependencies should be removed. This is problematic as the dependent txs may be unnecessarily removed from the txpool.

Expected behavior:

- when a block is imported
  - the txs that were successfully process should be removed and their dependencies should be kept
  - txs that were skipped should be removed along with any dependencies
 - when transactions are selected for block production
   - they should be removed without removing dependencies, but the depth of the dependencies should be updated
   - any skipped transactions from block production should also remove dependents in the txpool, although this should be handled by the same mechanism as block import

**Comment by xgreenx** [comment]
Related to https://github.com/FuelLabs/fuel-core/issues/1229

**Comment by xgreenx** [comment]
Done in https://github.com/FuelLabs/fuel-core/pull/2263
