### ISSUE TITLE
Implement IntoDatabaseKey for all keys and use `type Type = MultiKey` for tuples.

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-core#923]
This should also be made into an issue after this PR is merged for better tracking

_Originally posted by @ControlCplusControlV in https://github.com/FuelLabs/fuel-core/pull/915#discussion_r1083540828_

**Comment by xgreenx** [comment]
Fixed in the https://github.com/FuelLabs/fuel-core/pull/939
