### ISSUE TITLE
test_case's should be documented with human readable descriptions, ie.

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#940]
test_case's should be documented with human readable descriptions, ie.

`#[test_case(...; "successfully imports genesis block when database is empty")`

_Originally posted by @Voxelot in https://github.com/FuelLabs/fuel-core/pull/935#discussion_r1087348155_

**Comment by xgreenx** [comment]
Fixed with https://github.com/FuelLabs/fuel-core/pull/1286
