### ISSUE TITLE
Test suite is too slow

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-core#981]
Our full test sweet is taking too long to run. Especially the p2p tests. This slows down our development cycle and leads to avoiding running the entire suite.

**Comment by Voxelot** [comment]
Using cargo nextest our suite only takes 19s on my ryzen 5950x

**Comment by freesig** [comment]
Is that with the p2p feature also this isn't really a solution. Our test suite is slow because of the timing of the p2p tests which can be lowered for testing instead of just relying on running in on multiple threads. For example the CI currently takes [14 mins](https://github.com/FuelLabs/fuel-core/actions/runs/4108115643/jobs/7088430635) to run just the cargo test.

**Comment by xgreenx** [comment]
We run tests very fast after https://github.com/FuelLabs/fuel-core/pull/1231. But we still spend a lot of time building tests per crate https://github.com/FuelLabs/fuel-core/pull/987. But it is a problem during the first build without a cache, so doesn't hurt too much for follow-up commits. 

I close this issue for now.
