### ISSUE TITLE
Not to allow storing `Database` and `Relayer` inside of `Executor`

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-core#992]
The idea is not to allow storing `Database` and `Relayer` inside of `Executor`. Otherwise, it means that almost all services depend on the `Database` and `Relayer`. `Executor` should receive `Database` and `Relayer` from upper services. In this case, we don't have the assumption that the caller of the executor has the same `Relayer` and `Database`. Also, passing `Database` and `Relayer` gives much more flexibility(we already can pass the database transaction with some state inside).

You are right. It would be heavy to make this change in this PR.
We need to create a follow-up PR, where:
- Rename `Executor` into `ExecutorInner`.
- Make `ExecutorInner` a private type(in this case we don't need to update unit tests).
- Create a new `Executor` type that stores only config inside and provides the method `execute_without_commit`.
- `Executor:: execute_without_commit` will accept also `Database` and `Relayer`.
- `Executor:: execute_without_commit` creates `ExecutorInner` for one execution inside.

With this approach, `ExecutorInner` and `Executor` own `Database` and `Relayer` only during execution.

_Originally posted by @xgreenx in https://github.com/FuelLabs/fuel-core/pull/971#discussion_r1096164667_

**Comment by xgreenx** [comment]
Will be done with the https://github.com/FuelLabs/fuel-core/issues/1139
